apiVersion: 1
contactPoints:
  - name: liquidity-alerts-email
    receivers:
      - uid: email-receiver-01
        type: email
        settings:
          addresses: "lps-alerts@localhost.com"
          subject: "URGENT: LPS Alert - {{ .GroupLabels.operation_type | title }}"
          body: |
            {{ if eq .GroupLabels.operation_type "penalization" }}
            PENALIZATION ALERT
            
            The Liquidity Provider has been penalized!
            
            {{ range .Alerts }}
            - {{ .Annotations.description }}
            {{ end }}
            
            {{ else }}
            LIQUIDITY SHORTAGE ALERT
            
            Alert: {{ .GroupLabels.operation_type | title }} Liquidity Shortage
            Environment: Local
            
            {{ range .Alerts }}
            - {{ .Annotations.description }}
            {{ end }}
            
            {{ end }}
            Time: {{ .CommonAnnotations.time }} 