apiVersion: 1
policies:
  - orgId: 1
    receiver: liquidity-alerts-email
    group_by:
      - alertname
      - operation_type
    group_wait: 5s
    group_interval: 30s
    repeat_interval: 1m
    matchers:
      - severity = critical 