apiVersion: 1
groups:
  - name: lps-liquidity-alerts
    title: "LPS Liquidity Alerts"
    folder: "LPS"
    interval: 30s
    rules:
      - uid: pegin-liquidity-shortage
        title: "PegIn Liquidity Shortage"
        condition: B
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: loki-uid
            model:
              expr: 'count_over_time({service="lps"} |~ "Alert! - Subject: PegIn: Out of liquidity" [1m])'
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [0]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
        noDataState: NoData
        execErrState: Alerting
        for: 0s
        annotations:
          summary: "PegIn Liquidity Shortage Detected"
          description: "PegIn operations cannot be processed due to insufficient Bitcoin liquidity"
        labels:
          severity: critical
          operation_type: pegin
          
      - uid: pegout-liquidity-shortage
        title: "PegOut Liquidity Shortage"
        condition: B
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 60
              to: 0
            datasourceUid: loki-uid
            model:
              expr: 'count_over_time({service="lps"} |~ "Alert! - Subject: PegOut: Out of liquidity" [1m])'
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [0]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
        noDataState: NoData
        execErrState: Alerting
        for: 0s
        annotations:
          summary: "PegOut Liquidity Shortage Detected"
          description: "PegOut operations cannot be processed due to insufficient rBTC liquidity"
        labels:
          severity: critical
          operation_type: pegout 