run:
  allow-parallel-runners: true
  timeout: 3m
  tests: true
issues:
  exclude-dirs:
    - internal/adapters/dataproviders/rootstock/bindings/discovery
    - internal/adapters/dataproviders/rootstock/bindings/pegin
    - internal/adapters/dataproviders/rootstock/bindings/pegout
    - internal/adapters/dataproviders/rootstock/bindings/collateral_management
    - internal/adapters/dataproviders/rootstock/bindings/flyover
    - internal/adapters/dataproviders/rootstock/bindings/bridge
    - test/mocks
linters:
  presets:
    - bugs
    - complexity
    - unused
    - performance
linters-settings:
  errcheck:
   check-type-assertions: true
   check-blank: true
  govet:
    enable:
      - nilness
      - defers
      - lostcancel
      - nilfunc
      - shadow
      - unusedwrite
  exhaustive:
    default-signifies-exhaustive: true
  gosec:
    excludes:
      - G115 # TODO update project to cast safely