run:
  allow-parallel-runners: true
  timeout: 3m
  tests: true
  skip-dirs:
    - internal/adapters/dataproviders/rootstock/bindings
linters:
  presets:
    - bugs
    - complexity
    - unused
    - performance
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  gosec:
    excludes:
      - G115 # TODO update project to cast safely