with-expecter: true
dir: test/mocks
filename: "{{ .InterfaceName | snakecase }}_mock.go"
mockname: "{{ .InterfaceName | firstUpper }}Mock"
outpkg: mocks
packages:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/alerting:
    interfaces:
      sesClient:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/dataproviders/rootstock:
    interfaces:
      LbcBinding:
      RskBridgeBinding:
      TransactionSigner:
      RpcClientBinding:
      LbcCallerBinding:
      LbcAdapter:
      EventIteratorAdapter:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/dataproviders/bitcoin/btcclient:
    interfaces:
      RpcClient:
      ClientAdapter:
  github.com/rsksmart/liquidity-provider-server/internal/usecases/liquidity_provider:
    interfaces:
      DefaultCredentialsProvider:
  github.com/rsksmart/liquidity-provider-server/internal/entities/liquidity_provider:
    interfaces:
      LiquidityProviderRepository:
  github.com/rsksmart/liquidity-provider-server/internal/entities/quote:
      interfaces:
        PeginQuoteRepository:
        PegoutQuoteRepository:
  github.com/rsksmart/liquidity-provider-server/internal/entities/blockchain:
    interfaces:
      BitcoinWallet:
      RootstockRpcServer: