with-expecter: true
dir: test/mocks
filename: "{{ .InterfaceName | snakecase }}_mock.go"
mockname: "{{ .InterfaceName | firstUpper }}Mock"
outpkg: mocks
packages:
  github.com/rsksmart/liquidity-provider-server/internal/configuration/bootstrap/wallet:
    interfaces:
      AbstractFactory:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/alerting:
    interfaces:
      sesClient:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/dataproviders/rootstock:
    interfaces:
      LbcBinding:
      RskBridgeBinding:
      TransactionSigner:
      RpcClientBinding:
      LbcCallerBinding:
      LbcAdapter:
      EventIteratorAdapter:
      RskSignerWallet:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/dataproviders/database/mongo:
    interfaces:
      DbClientBinding:
      DbBinding:
      CollectionBinding:
      SessionBinding:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/dataproviders/bitcoin/btcclient:
    interfaces:
      RpcClient:
      ClientAdapter:
  github.com/rsksmart/liquidity-provider-server/internal/usecases/liquidity_provider:
    interfaces:
      DefaultCredentialsProvider:
  github.com/rsksmart/liquidity-provider-server/internal/entities/liquidity_provider:
    interfaces:
      LiquidityProviderRepository:
  github.com/rsksmart/liquidity-provider-server/internal/entities/quote:
      interfaces:
        PeginQuoteRepository:
        PegoutQuoteRepository:
  github.com/rsksmart/liquidity-provider-server/internal/entities/blockchain:
    interfaces:
      BitcoinWallet:
      RootstockRpcServer:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/dataproviders/utils:
    interfaces:
      HttpClient:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/entrypoints/watcher:
    interfaces:
      Ticker:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/entrypoints/rest/registry:
    interfaces:
      UseCaseRegistry:
  github.com/gorilla/sessions:
    interfaces:
      Store: