with-expecter: true
dir: test/mocks
resolve-type-alias: false
issue-845-fix: true
filename: "{{ .InterfaceName | snakecase }}_mock.go"
mockname: "{{ .InterfaceName | firstUpper }}Mock"
outpkg: mocks
packages:
  github.com/rsksmart/liquidity-provider-server/internal/configuration/bootstrap/wallet:
    interfaces:
      AbstractFactory:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/alerting:
    interfaces:
      sesClient:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/dataproviders/rootstock:
    interfaces:
      LbcBinding:
      RskBridgeBinding:
      TransactionSigner:
      RpcClientBinding:
      LbcCallerBinding:
      LbcAdapter:
      RskBridgeAdapter:
      EventIteratorAdapter:
      RskSignerWallet:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/dataproviders/database/mongo:
    interfaces:
      DbClientBinding:
      DbBinding:
      CollectionBinding:
      SessionBinding:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/dataproviders/bitcoin/btcclient:
    interfaces:
      RpcClient:
      ClientAdapter:
  github.com/rsksmart/liquidity-provider-server/internal/usecases/liquidity_provider:
    interfaces:
      DefaultCredentialsProvider:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/entrypoints/rest/handlers:
    interfaces:
      AddPeginCollateralUseCase:
      AddPegoutCollateralUseCase:
      ChangeStatusUseCase:
      GetAssetsReportUseCase:
      GetAvailableLiquidityUseCase:
      GetConfigUseCase:
      GetPeginCollateralUseCase:
      GetPeginQuoteUseCase:
      GetPegoutCollateralUseCase:
      GetPegoutQuoteUseCase:
      GetProvidersUseCase:
      PeginStatusUseCase:
      PegoutStatusUseCase:
      SetGeneralConfigUseCase:
      GetPegoutReportUseCase:
      GetPeginReportUseCase:
      RecommendedPegoutUseCase:
      RecommendedPeginUseCase:
      ResignUseCase:
      GetRevenueReportUseCase:
      GetSummariesReportUseCase:
      WithdrawCollateralUseCase:
  github.com/rsksmart/liquidity-provider-server/internal/entities/liquidity_provider:
    interfaces:
      LiquidityProviderRepository:
      TrustedAccountRepository:
  github.com/rsksmart/liquidity-provider-server/internal/entities/penalization:
    interfaces:
      PenalizedEventRepository:
  github.com/rsksmart/liquidity-provider-server/internal/entities/quote:
      interfaces:
        PeginQuoteRepository:
        PegoutQuoteRepository:
        PegConfiguration:
  github.com/rsksmart/liquidity-provider-server/internal/entities/blockchain:
    interfaces:
      BitcoinWallet:
      RootstockRpcServer:
      LiquidityBridgeContract:
  github.com/rsksmart/liquidity-provider-server/internal/entities/rootstock:
    interfaces:
      BatchPegOutRepository:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/dataproviders/utils:
    interfaces:
      HttpClient:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/entrypoints/rest/registry:
    interfaces:
      UseCaseRegistry:
  github.com/gorilla/sessions:
    interfaces:
      Store:
  net/http:
    interfaces:
      Handler:
  github.com/rsksmart/liquidity-provider-server/internal/entities/utils:
    interfaces:
      Ticker:
      Timer:
  github.com/rsksmart/liquidity-provider-server/internal/adapters/entrypoints/watcher:
    interfaces:
      EclipseCheckUseCase:
      UpdateBtcReleaseUseCase:
