{
 "title": "Flyover - Liquidity Provider Server",
 "description": "Dashboard to monitor an instance of the Liquidity Provider Server of the Flyover Protocol",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "label_values(go_info, job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(go_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Liquidity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total liquidity",
     "type": "bargauge",
     "description": "Total liquidity in the protocol",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"rbtc\", type=\"total\"}",
       "legendFormat": "RBTC"
      },
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"btc\", type=\"total\"}",
       "legendFormat": "BTC"
      }
     ]
    },
    {
     "title": "Total liquidity",
     "type": "stat",
     "description": "Total liquidity in the protocol",
     "gridPos": { "h": 5, "w": 7, "x": 16, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(type) (lps_assets_balances{job=\"$job\", instance=~\"$instance\", type=\"total\"})",
       "legendFormat": "RBTC"
      }
     ]
    },
    {
     "title": "Total liquidity across time",
     "type": "timeseries",
     "description": "Total liquidity across time in the protocol ",
     "gridPos": { "h": 5, "w": 23, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"rbtc\", type=\"total\"}",
       "legendFormat": "RBTC"
      },
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"btc\", type=\"total\"}",
       "legendFormat": "BTC"
      }
     ]
    },
    {
     "title": "RBTC Liquidity Distribution",
     "type": "piechart",
     "description": "Distribution of the current RBTC Liquidity. This means where is each portion of the RBTC.",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"rbtc\", type=\"location_rsk_wallet\"}",
       "legendFormat": "Wallet"
      },
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"rbtc\", type=\"location_lbc\"}",
       "legendFormat": "Contract"
      },
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"rbtc\", type=\"location_federation\"}",
       "legendFormat": "Federation"
      }
     ]
    },
    {
     "title": "RBTC Liquidity Allocation",
     "type": "piechart",
     "description": "Allocation of the current RBTC liquidity. This shows which portion of the liquidity is actually usable.",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 77 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"rbtc\", type=\"allocation_available\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"rbtc\", type=\"allocation_waiting_refund\"}",
       "legendFormat": "Waiting for refund"
      },
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"rbtc\", type=\"allocation_reserved_for_users\"}",
       "legendFormat": "Reserved"
      }
     ]
    },
    {
     "title": "BTC Liquidity Distribution",
     "type": "piechart",
     "description": "Distribution of the current BTC liquidity. This means where is each portion of the BTC.",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"btc\", type=\"location_btc_wallet\"}",
       "legendFormat": "BTC Wallet"
      },
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"btc\", type=\"location_federation\"}",
       "legendFormat": "Rebalancing"
      },
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"btc\", type=\"location_rsk_wallet\"}",
       "legendFormat": "Waiting for rebalance"
      },
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"btc\", type=\"location_lbc\"}",
       "legendFormat": "Waiting for refund"
      }
     ]
    },
    {
     "title": "BTC Liquidity Allocation",
     "type": "piechart",
     "description": "Allocation of the current BTC liquidity. This shows which portion of the liquidity is actually usable.",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"btc\", type=\"allocation_available\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"btc\", type=\"allocation_waiting_refund\"}",
       "legendFormat": "Waiting for refund"
      },
      {
       "expr": "lps_assets_balances{job=\"$job\", instance=~\"$instance\", currency=\"btc\", type=\"allocation_reserved_for_users\"}",
       "legendFormat": "Reserved"
      }
     ]
    }
   ]
  },
  {
   "title": "Quotes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "PegIn Quotes",
     "type": "piechart",
     "description": "Distribution of the current PegIn quotes",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (lps_pegin_quotes{job=\"$job\", instance=~\"$instance\", state=\"lp_refunded\"})  or vector(0)",
       "legendFormat": "Refunded"
      },
      {
       "expr": "(sum (lps_pegin_quotes{job=\"$job\", instance=~\"$instance\", state=\"paid\"}) or vector(0)) - (sum (lps_pegin_quotes{job=\"$job\", instance=~\"$instance\", state=\"lp_refunded\"}) or vector(0))",
       "legendFormat": "Paid"
      },
      {
       "expr": "(sum (lps_pegin_quotes{job=\"$job\", instance=~\"$instance\", state=\"accepted\"}) or vector(0)) - (sum (lps_pegin_quotes{job=\"$job\", instance=~\"$instance\", state=\"paid\"}) or vector(0))",
       "legendFormat": "Accepted"
      }
     ]
    },
    {
     "title": "PegOut Quotes",
     "type": "piechart",
     "description": "Distribution of the current PegOut quotes",
     "gridPos": { "h": 8, "w": 11, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (lps_pegout_quotes{job=\"$job\", instance=~\"$instance\", state=\"lp_refunded\"}) or vector(0)",
       "legendFormat": "Refunded"
      },
      {
       "expr": "(sum (lps_pegout_quotes{job=\"$job\", instance=~\"$instance\", state=\"paid\"}) or vector(0)) - (sum (lps_pegout_quotes{job=\"$job\", instance=~\"$instance\", state=\"lp_refunded\"}) or vector(0))",
       "legendFormat": "Paid"
      },
      {
       "expr": "(sum (lps_pegout_quotes{job=\"$job\", instance=~\"$instance\", state=\"accepted\"}) or vector(0)) - (sum (lps_pegout_quotes{job=\"$job\", instance=~\"$instance\", state=\"paid\"}) or vector(0))",
       "legendFormat": "Accepted"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Level Distribution",
     "type": "piechart",
     "description": "Distribution of log levels in LPS application",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "direction": "backward",
       "expr": "sum by (level) (count_over_time({service_name=\"lps\"}| pattern `<time> level=<level> <message>` [$__range]))",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "LPS Application Logs",
     "type": "logs",
     "description": "Recent LPS application logs from all log levels",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "direction": "forward",
       "expr": "{service_name=\"lps\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Liquidity Provider Server Version",
     "type": "stat",
     "description": "Version of the LPS. If the value is \"Not provided\" means that such information was not included during the compilation of the server.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lps_server_info{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Liquidity Provider Server revision",
     "type": "stat",
     "description": "Commit of the LPS build. If the value is \"Not provided\" means that such information was not included during the compilation of the server.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "lps_server_info{job=\"$job\", instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Reserved Memory",
     "type": "timeseries",
     "description": "Average total bytes of memory reserved across all process instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 431 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by(job)(go_memstats_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}} (avg)"
      }
     ]
    },
    {
     "title": "Heap Memory",
     "type": "timeseries",
     "description": "Average memory reserved, and actually in use, by the heap, across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 431 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (job)(go_memstats_heap_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: heap reserved (avg)"
      },
      {
       "expr": "avg by (job)(go_memstats_heap_inuse_bytes{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: heap in use (avg)"
      },
      {
       "expr": "avg by (job)(go_memstats_heap_alloc_bytes{job=~\"$job\",instance=~\".*\"})",
       "legendFormat": "{{job}}: heap alloc (avg)"
      },
      {
       "expr": "avg by (job)(go_memstats_heap_idle_bytes{job=~\"$job\",instance=~\".*\"})",
       "legendFormat": "{{job}}: heap idle (avg)"
      },
      {
       "expr": "avg by (job)(go_memstats_heap_released_bytes{job=~\"$job\",instance=~\".*\"})",
       "legendFormat": "{{job}}: heap released (avg)"
      }
     ]
    },
    {
     "title": "Other Memory Reservations",
     "type": "timeseries",
     "description": "Average memory reservations by the runtime, not for stack or heap, across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 439 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (job)(go_memstats_mspan_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}: mspan (avg)"
      },
      {
       "expr": "avg by (job)(go_memstats_mcache_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}: mcache (avg)"
      },
      {
       "expr": "avg by (job)(go_memstats_buck_hash_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{instance}}: buck hash (avg)"
      },
      {
       "expr": "avg by (job)(go_memstats_gc_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: gc (avg)"
      }
     ]
    },
    {
     "title": "Heap Object Allocation Rate",
     "type": "timeseries",
     "description": "Average rate of heap object allocation, across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 439 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{job}}: obj mallocs/s (avg)"
      }
     ]
    },
    {
     "title": "Allocation Rate, Bytes",
     "type": "timeseries",
     "description": "Average allocation rate in bytes per second, across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 447 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg by (job)(rate(go_memstats_alloc_bytes_total{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{job}}: bytes malloced/s (avg)"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "description": "Average number of goroutines across instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 447 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (job)(go_goroutines{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: goroutine count (avg)"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "description": "Average number of live memory objects across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 455 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(job)(go_memstats_mallocs_total{job=\"$job\", instance=~\"$instance\"} - go_memstats_frees_total{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: object count (avg)"
      }
     ]
    },
    {
     "title": "Next GC, Bytes",
     "type": "timeseries",
     "description": "The number used bytes at which the runtime plans to perform the next GC, averaged across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 455 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (job)(go_memstats_next_gc_bytes{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}} next gc bytes (avg)"
      }
     ]
    },
    {
     "title": "GC min & max duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 463 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (job)(go_gc_duration_seconds{quantile=\"0\", job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: min gc time (avg)"
      },
      {
       "expr": "avg by (job)(go_gc_duration_seconds{quantile=\"1\", job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: max gc time (avg)"
      }
     ]
    },
    {
     "title": "Stack Memory Use",
     "type": "timeseries",
     "description": "Average stack memory usage across all instances of a job.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 463 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by (job) (go_memstats_stack_sys_bytes{job=\"$job\", instance=~\"$instance\"})",
       "legendFormat": "{{job}}: stack inuse (avg)"
      }
     ]
    }
   ]
  }
 ]
}