services:
  localstack:
    build:
      context: ./localstack
      args:
        UID: "${LPS_UID}"
    pull_policy: build
    container_name: localstack
    image: flyover-localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_HOME:-./volumes/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net_lps
  bitcoind:
    build:
      context: ../bitcoind
      args:
        UID: "${LPS_UID}"
    pull_policy: build
    image: bitcond:latest
    container_name: bitcoind01
    environment:
      - BTC_USERNAME
      - BTC_PASSWORD
    ports:
      - "5555:5555"
    volumes:
      - ${BTCD_HOME:-./volumes/bitcoind}:/home/bitcoind/.bitcoind
    networks:
      - net_lps
    command:
      [
        "bitcoind",
        "-rpcuser=${BTC_USERNAME}",
        "-rpcpassword=${BTC_PASSWORD}",
        "-addresstype=legacy",
        "-${LPS_STAGE}",
        "-printtoconsole",
        "-server",
        "-txindex",
        "-deprecatedrpc=signrawtransaction",
        "-deprecatedrpc=accounts",
        "-rpcbind=0.0.0.0",
        "-rpcallowip=0.0.0.0/0",
        "-rpcport=5555",
      ]
  rskj:
    build:
      context: ../rskj
      args:
        UID: "${LPS_UID}"
    pull_policy: build
    image: rskj:latest
    container_name: rskj01
    ports:
      - "4444:4444"
      - "4445:4445"
    volumes:
      - ${RSKJ_HOME:-./volumes/rskj}/db:/var/lib/rsk/database
      - ${RSKJ_HOME:-./volumes/rskj}/logs:/var/log/rsk
    networks:
      - net_lps
    command:
      [
        "--${LPS_STAGE}",
      ]
  mongodb:
    image: mongo:4
    restart: on-failure
    container_name: mongo01
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=flyover
    ports:
      - 27017:27017
    volumes:
      - ${MONGO_HOME:-./volumes/mongo}/logs:/data/db
    expose:
      - 27017
    networks:
      - net_lps

networks:
  net_lps:
    driver: "bridge"
