---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine
    tag: 3

inputs:
- name: repo-iac-ng
- name: repo-liquidity-provider-server

outputs:
- name: out

params:
  SSH_DEPLOY_KEY: ((ssh-deploy))
  ANSIBLE_HOST_KEY_CHECKING: false

run:
  path: sh
  args:
  - -ceux
  - |
    out_message_file=$(pwd)/out/message.txt
    apk add -q --no-progress openssh ansible gnupg git
    
    cd repo-liquidity-provider-server
    git checkout master
    cd ..

    echo "Liquidity-provider-server deployment to mainnet" > $out_message_file

    ssh_deploy_keyfile=$(pwd)/ssh_deploy_key

    umask 077
    echo "$SSH_DEPLOY_KEY" > $ssh_deploy_keyfile
    umask 022
    
    eval $(ssh-agent)
    ssh-add $ssh_deploy_keyfile

    cd repo-iac-ng/ansible

    ansible-playbook -i inventory/ -l flyover-01.aws-us-east-1.mainnet.flyover.rifcomputing.net -e ansible_ssh_extra_args=-oForwardAgent=yes deploy-flyover.yml
