services:
  fed-migrator:
    build:
      context: ./fed-migrator
    pull_policy: build
    image: fed-migrator:latest
    volumes:
      - ./fed-migrator/scripts:/scripts
      - ./${ENV_FILE}:/${ENV_FILE}
    command: ["node", "/scripts/migrateFederationToSegwit.js"]
    restart: "no"
    container_name: fed-migrator
    environment:
      - RSK_ENDPOINT
      - ENV_FILE
      - BTC_RPC_URL=http://bitcoind:5555
      - BTC_RPC_USER=test
      - BTC_RPC_PASSWORD=test
      - BTC_RPC_WALLET=main
      - BTC_WALLET_PASSPHRASE=test-password
    networks:
      - net_lps
networks:
  net_lps:
    driver: "bridge"
