// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	quote "github.com/rsksmart/liquidity-provider-server/internal/entities/quote"
)

// AcceptQuoteUseCaseMock is an autogenerated mock type for the AcceptQuoteUseCase type
type AcceptQuoteUseCaseMock struct {
	mock.Mock
}

type AcceptQuoteUseCaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AcceptQuoteUseCaseMock) EXPECT() *AcceptQuoteUseCaseMock_Expecter {
	return &AcceptQuoteUseCaseMock_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, quoteHash, signature
func (_m *AcceptQuoteUseCaseMock) Run(ctx context.Context, quoteHash string, signature string) (quote.AcceptedQuote, error) {
	ret := _m.Called(ctx, quoteHash, signature)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 quote.AcceptedQuote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (quote.AcceptedQuote, error)); ok {
		return rf(ctx, quoteHash, signature)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) quote.AcceptedQuote); ok {
		r0 = rf(ctx, quoteHash, signature)
	} else {
		r0 = ret.Get(0).(quote.AcceptedQuote)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, quoteHash, signature)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AcceptQuoteUseCaseMock_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type AcceptQuoteUseCaseMock_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - quoteHash string
//   - signature string
func (_e *AcceptQuoteUseCaseMock_Expecter) Run(ctx interface{}, quoteHash interface{}, signature interface{}) *AcceptQuoteUseCaseMock_Run_Call {
	return &AcceptQuoteUseCaseMock_Run_Call{Call: _e.mock.On("Run", ctx, quoteHash, signature)}
}

func (_c *AcceptQuoteUseCaseMock_Run_Call) Run(run func(ctx context.Context, quoteHash string, signature string)) *AcceptQuoteUseCaseMock_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AcceptQuoteUseCaseMock_Run_Call) Return(_a0 quote.AcceptedQuote, _a1 error) *AcceptQuoteUseCaseMock_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AcceptQuoteUseCaseMock_Run_Call) RunAndReturn(run func(context.Context, string, string) (quote.AcceptedQuote, error)) *AcceptQuoteUseCaseMock_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewAcceptQuoteUseCaseMock creates a new instance of AcceptQuoteUseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAcceptQuoteUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AcceptQuoteUseCaseMock {
	mock := &AcceptQuoteUseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
