// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	entities "github.com/rsksmart/liquidity-provider-server/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// AddPeginCollateralUseCaseMock is an autogenerated mock type for the AddPeginCollateralUseCase type
type AddPeginCollateralUseCaseMock struct {
	mock.Mock
}

type AddPeginCollateralUseCaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AddPeginCollateralUseCaseMock) EXPECT() *AddPeginCollateralUseCaseMock_Expecter {
	return &AddPeginCollateralUseCaseMock_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: amount
func (_m *AddPeginCollateralUseCaseMock) Run(amount *entities.Wei) (*entities.Wei, error) {
	ret := _m.Called(amount)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 *entities.Wei
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.Wei) (*entities.Wei, error)); ok {
		return rf(amount)
	}
	if rf, ok := ret.Get(0).(func(*entities.Wei) *entities.Wei); ok {
		r0 = rf(amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wei)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.Wei) error); ok {
		r1 = rf(amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddPeginCollateralUseCaseMock_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type AddPeginCollateralUseCaseMock_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - amount *entities.Wei
func (_e *AddPeginCollateralUseCaseMock_Expecter) Run(amount interface{}) *AddPeginCollateralUseCaseMock_Run_Call {
	return &AddPeginCollateralUseCaseMock_Run_Call{Call: _e.mock.On("Run", amount)}
}

func (_c *AddPeginCollateralUseCaseMock_Run_Call) Run(run func(amount *entities.Wei)) *AddPeginCollateralUseCaseMock_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Wei))
	})
	return _c
}

func (_c *AddPeginCollateralUseCaseMock_Run_Call) Return(_a0 *entities.Wei, _a1 error) *AddPeginCollateralUseCaseMock_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AddPeginCollateralUseCaseMock_Run_Call) RunAndReturn(run func(*entities.Wei) (*entities.Wei, error)) *AddPeginCollateralUseCaseMock_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewAddPeginCollateralUseCaseMock creates a new instance of AddPeginCollateralUseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddPeginCollateralUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddPeginCollateralUseCaseMock {
	mock := &AddPeginCollateralUseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
