// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	ethereum "github.com/ethereum/go-ethereum"
	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// ContractFiltererMock is an autogenerated mock type for the ContractFilterer type
type ContractFiltererMock struct {
	mock.Mock
}

type ContractFiltererMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ContractFiltererMock) EXPECT() *ContractFiltererMock_Expecter {
	return &ContractFiltererMock_Expecter{mock: &_m.Mock}
}

// FilterLogs provides a mock function with given fields: ctx, q
func (_m *ContractFiltererMock) FilterLogs(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for FilterLogs")
	}

	var r0 []types.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery) ([]types.Log, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery) []types.Log); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ethereum.FilterQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContractFiltererMock_FilterLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterLogs'
type ContractFiltererMock_FilterLogs_Call struct {
	*mock.Call
}

// FilterLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - q ethereum.FilterQuery
func (_e *ContractFiltererMock_Expecter) FilterLogs(ctx interface{}, q interface{}) *ContractFiltererMock_FilterLogs_Call {
	return &ContractFiltererMock_FilterLogs_Call{Call: _e.mock.On("FilterLogs", ctx, q)}
}

func (_c *ContractFiltererMock_FilterLogs_Call) Run(run func(ctx context.Context, q ethereum.FilterQuery)) *ContractFiltererMock_FilterLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ethereum.FilterQuery))
	})
	return _c
}

func (_c *ContractFiltererMock_FilterLogs_Call) Return(_a0 []types.Log, _a1 error) *ContractFiltererMock_FilterLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContractFiltererMock_FilterLogs_Call) RunAndReturn(run func(context.Context, ethereum.FilterQuery) ([]types.Log, error)) *ContractFiltererMock_FilterLogs_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeFilterLogs provides a mock function with given fields: ctx, q, ch
func (_m *ContractFiltererMock) SubscribeFilterLogs(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error) {
	ret := _m.Called(ctx, q, ch)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeFilterLogs")
	}

	var r0 ethereum.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery, chan<- types.Log) (ethereum.Subscription, error)); ok {
		return rf(ctx, q, ch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ethereum.FilterQuery, chan<- types.Log) ethereum.Subscription); ok {
		r0 = rf(ctx, q, ch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ethereum.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ethereum.FilterQuery, chan<- types.Log) error); ok {
		r1 = rf(ctx, q, ch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ContractFiltererMock_SubscribeFilterLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeFilterLogs'
type ContractFiltererMock_SubscribeFilterLogs_Call struct {
	*mock.Call
}

// SubscribeFilterLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - q ethereum.FilterQuery
//   - ch chan<- types.Log
func (_e *ContractFiltererMock_Expecter) SubscribeFilterLogs(ctx interface{}, q interface{}, ch interface{}) *ContractFiltererMock_SubscribeFilterLogs_Call {
	return &ContractFiltererMock_SubscribeFilterLogs_Call{Call: _e.mock.On("SubscribeFilterLogs", ctx, q, ch)}
}

func (_c *ContractFiltererMock_SubscribeFilterLogs_Call) Run(run func(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log)) *ContractFiltererMock_SubscribeFilterLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ethereum.FilterQuery), args[2].(chan<- types.Log))
	})
	return _c
}

func (_c *ContractFiltererMock_SubscribeFilterLogs_Call) Return(_a0 ethereum.Subscription, _a1 error) *ContractFiltererMock_SubscribeFilterLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ContractFiltererMock_SubscribeFilterLogs_Call) RunAndReturn(run func(context.Context, ethereum.FilterQuery, chan<- types.Log) (ethereum.Subscription, error)) *ContractFiltererMock_SubscribeFilterLogs_Call {
	_c.Call.Return(run)
	return _c
}

// NewContractFiltererMock creates a new instance of ContractFiltererMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContractFiltererMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContractFiltererMock {
	mock := &ContractFiltererMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
