// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mongo "github.com/rsksmart/liquidity-provider-server/internal/adapters/dataproviders/database/mongo"
	mock "github.com/stretchr/testify/mock"
	options "go.mongodb.org/mongo-driver/mongo/options"

	readpref "go.mongodb.org/mongo-driver/mongo/readpref"
)

// DbClientBindingMock is an autogenerated mock type for the DbClientBinding type
type DbClientBindingMock struct {
	mock.Mock
}

type DbClientBindingMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DbClientBindingMock) EXPECT() *DbClientBindingMock_Expecter {
	return &DbClientBindingMock_Expecter{mock: &_m.Mock}
}

// Database provides a mock function with given fields: name, opts
func (_m *DbClientBindingMock) Database(name string, opts ...*options.DatabaseOptions) mongo.DbBinding {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Database")
	}

	var r0 mongo.DbBinding
	if rf, ok := ret.Get(0).(func(string, ...*options.DatabaseOptions) mongo.DbBinding); ok {
		r0 = rf(name, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mongo.DbBinding)
		}
	}

	return r0
}

// DbClientBindingMock_Database_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Database'
type DbClientBindingMock_Database_Call struct {
	*mock.Call
}

// Database is a helper method to define mock.On call
//   - name string
//   - opts ...*options.DatabaseOptions
func (_e *DbClientBindingMock_Expecter) Database(name interface{}, opts ...interface{}) *DbClientBindingMock_Database_Call {
	return &DbClientBindingMock_Database_Call{Call: _e.mock.On("Database",
		append([]interface{}{name}, opts...)...)}
}

func (_c *DbClientBindingMock_Database_Call) Run(run func(name string, opts ...*options.DatabaseOptions)) *DbClientBindingMock_Database_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*options.DatabaseOptions, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(*options.DatabaseOptions)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *DbClientBindingMock_Database_Call) Return(_a0 mongo.DbBinding) *DbClientBindingMock_Database_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DbClientBindingMock_Database_Call) RunAndReturn(run func(string, ...*options.DatabaseOptions) mongo.DbBinding) *DbClientBindingMock_Database_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with given fields: ctx
func (_m *DbClientBindingMock) Disconnect(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DbClientBindingMock_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type DbClientBindingMock_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DbClientBindingMock_Expecter) Disconnect(ctx interface{}) *DbClientBindingMock_Disconnect_Call {
	return &DbClientBindingMock_Disconnect_Call{Call: _e.mock.On("Disconnect", ctx)}
}

func (_c *DbClientBindingMock_Disconnect_Call) Run(run func(ctx context.Context)) *DbClientBindingMock_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DbClientBindingMock_Disconnect_Call) Return(_a0 error) *DbClientBindingMock_Disconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DbClientBindingMock_Disconnect_Call) RunAndReturn(run func(context.Context) error) *DbClientBindingMock_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx, rp
func (_m *DbClientBindingMock) Ping(ctx context.Context, rp *readpref.ReadPref) error {
	ret := _m.Called(ctx, rp)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *readpref.ReadPref) error); ok {
		r0 = rf(ctx, rp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DbClientBindingMock_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type DbClientBindingMock_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - rp *readpref.ReadPref
func (_e *DbClientBindingMock_Expecter) Ping(ctx interface{}, rp interface{}) *DbClientBindingMock_Ping_Call {
	return &DbClientBindingMock_Ping_Call{Call: _e.mock.On("Ping", ctx, rp)}
}

func (_c *DbClientBindingMock_Ping_Call) Run(run func(ctx context.Context, rp *readpref.ReadPref)) *DbClientBindingMock_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*readpref.ReadPref))
	})
	return _c
}

func (_c *DbClientBindingMock_Ping_Call) Return(_a0 error) *DbClientBindingMock_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DbClientBindingMock_Ping_Call) RunAndReturn(run func(context.Context, *readpref.ReadPref) error) *DbClientBindingMock_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewDbClientBindingMock creates a new instance of DbClientBindingMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDbClientBindingMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DbClientBindingMock {
	mock := &DbClientBindingMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
