// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	entities "github.com/rsksmart/liquidity-provider-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// FlyoverConfigurationsContractMock is an autogenerated mock type for the FlyoverConfigurationsContract type
type FlyoverConfigurationsContractMock struct {
	mock.Mock
}

type FlyoverConfigurationsContractMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FlyoverConfigurationsContractMock) EXPECT() *FlyoverConfigurationsContractMock_Expecter {
	return &FlyoverConfigurationsContractMock_Expecter{mock: &_m.Mock}
}

// CalculatePegInFee provides a mock function with given fields: amount
func (_m *FlyoverConfigurationsContractMock) CalculatePegInFee(amount *entities.Wei) (*entities.Wei, error) {
	ret := _m.Called(amount)

	if len(ret) == 0 {
		panic("no return value specified for CalculatePegInFee")
	}

	var r0 *entities.Wei
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.Wei) (*entities.Wei, error)); ok {
		return rf(amount)
	}
	if rf, ok := ret.Get(0).(func(*entities.Wei) *entities.Wei); ok {
		r0 = rf(amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Wei)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.Wei) error); ok {
		r1 = rf(amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FlyoverConfigurationsContractMock_CalculatePegInFee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculatePegInFee'
type FlyoverConfigurationsContractMock_CalculatePegInFee_Call struct {
	*mock.Call
}

// CalculatePegInFee is a helper method to define mock.On call
//   - amount *entities.Wei
func (_e *FlyoverConfigurationsContractMock_Expecter) CalculatePegInFee(amount interface{}) *FlyoverConfigurationsContractMock_CalculatePegInFee_Call {
	return &FlyoverConfigurationsContractMock_CalculatePegInFee_Call{Call: _e.mock.On("CalculatePegInFee", amount)}
}

func (_c *FlyoverConfigurationsContractMock_CalculatePegInFee_Call) Run(run func(amount *entities.Wei)) *FlyoverConfigurationsContractMock_CalculatePegInFee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Wei))
	})
	return _c
}

func (_c *FlyoverConfigurationsContractMock_CalculatePegInFee_Call) Return(_a0 *entities.Wei, _a1 error) *FlyoverConfigurationsContractMock_CalculatePegInFee_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FlyoverConfigurationsContractMock_CalculatePegInFee_Call) RunAndReturn(run func(*entities.Wei) (*entities.Wei, error)) *FlyoverConfigurationsContractMock_CalculatePegInFee_Call {
	_c.Call.Return(run)
	return _c
}

// GetAddress provides a mock function with no fields
func (_m *FlyoverConfigurationsContractMock) GetAddress() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAddress")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// FlyoverConfigurationsContractMock_GetAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddress'
type FlyoverConfigurationsContractMock_GetAddress_Call struct {
	*mock.Call
}

// GetAddress is a helper method to define mock.On call
func (_e *FlyoverConfigurationsContractMock_Expecter) GetAddress() *FlyoverConfigurationsContractMock_GetAddress_Call {
	return &FlyoverConfigurationsContractMock_GetAddress_Call{Call: _e.mock.On("GetAddress")}
}

func (_c *FlyoverConfigurationsContractMock_GetAddress_Call) Run(run func()) *FlyoverConfigurationsContractMock_GetAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FlyoverConfigurationsContractMock_GetAddress_Call) Return(_a0 string) *FlyoverConfigurationsContractMock_GetAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FlyoverConfigurationsContractMock_GetAddress_Call) RunAndReturn(run func() string) *FlyoverConfigurationsContractMock_GetAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequiredPegInBtcConfirmations provides a mock function with given fields: amount
func (_m *FlyoverConfigurationsContractMock) GetRequiredPegInBtcConfirmations(amount *entities.Wei) (uint64, error) {
	ret := _m.Called(amount)

	if len(ret) == 0 {
		panic("no return value specified for GetRequiredPegInBtcConfirmations")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.Wei) (uint64, error)); ok {
		return rf(amount)
	}
	if rf, ok := ret.Get(0).(func(*entities.Wei) uint64); ok {
		r0 = rf(amount)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(*entities.Wei) error); ok {
		r1 = rf(amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FlyoverConfigurationsContractMock_GetRequiredPegInBtcConfirmations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequiredPegInBtcConfirmations'
type FlyoverConfigurationsContractMock_GetRequiredPegInBtcConfirmations_Call struct {
	*mock.Call
}

// GetRequiredPegInBtcConfirmations is a helper method to define mock.On call
//   - amount *entities.Wei
func (_e *FlyoverConfigurationsContractMock_Expecter) GetRequiredPegInBtcConfirmations(amount interface{}) *FlyoverConfigurationsContractMock_GetRequiredPegInBtcConfirmations_Call {
	return &FlyoverConfigurationsContractMock_GetRequiredPegInBtcConfirmations_Call{Call: _e.mock.On("GetRequiredPegInBtcConfirmations", amount)}
}

func (_c *FlyoverConfigurationsContractMock_GetRequiredPegInBtcConfirmations_Call) Run(run func(amount *entities.Wei)) *FlyoverConfigurationsContractMock_GetRequiredPegInBtcConfirmations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Wei))
	})
	return _c
}

func (_c *FlyoverConfigurationsContractMock_GetRequiredPegInBtcConfirmations_Call) Return(_a0 uint64, _a1 error) *FlyoverConfigurationsContractMock_GetRequiredPegInBtcConfirmations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FlyoverConfigurationsContractMock_GetRequiredPegInBtcConfirmations_Call) RunAndReturn(run func(*entities.Wei) (uint64, error)) *FlyoverConfigurationsContractMock_GetRequiredPegInBtcConfirmations_Call {
	_c.Call.Return(run)
	return _c
}

// NewFlyoverConfigurationsContractMock creates a new instance of FlyoverConfigurationsContractMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlyoverConfigurationsContractMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlyoverConfigurationsContractMock {
	mock := &FlyoverConfigurationsContractMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
