// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	quote "github.com/rsksmart/liquidity-provider-server/internal/entities/quote"
)

// GetUserDepositsUseCaseMock is an autogenerated mock type for the GetUserDepositsUseCase type
type GetUserDepositsUseCaseMock struct {
	mock.Mock
}

type GetUserDepositsUseCaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *GetUserDepositsUseCaseMock) EXPECT() *GetUserDepositsUseCaseMock_Expecter {
	return &GetUserDepositsUseCaseMock_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, address
func (_m *GetUserDepositsUseCaseMock) Run(ctx context.Context, address string) ([]quote.PegoutDeposit, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 []quote.PegoutDeposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]quote.PegoutDeposit, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []quote.PegoutDeposit); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]quote.PegoutDeposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserDepositsUseCaseMock_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type GetUserDepositsUseCaseMock_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *GetUserDepositsUseCaseMock_Expecter) Run(ctx interface{}, address interface{}) *GetUserDepositsUseCaseMock_Run_Call {
	return &GetUserDepositsUseCaseMock_Run_Call{Call: _e.mock.On("Run", ctx, address)}
}

func (_c *GetUserDepositsUseCaseMock_Run_Call) Run(run func(ctx context.Context, address string)) *GetUserDepositsUseCaseMock_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GetUserDepositsUseCaseMock_Run_Call) Return(_a0 []quote.PegoutDeposit, _a1 error) *GetUserDepositsUseCaseMock_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetUserDepositsUseCaseMock_Run_Call) RunAndReturn(run func(context.Context, string) ([]quote.PegoutDeposit, error)) *GetUserDepositsUseCaseMock_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetUserDepositsUseCaseMock creates a new instance of GetUserDepositsUseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetUserDepositsUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetUserDepositsUseCaseMock {
	mock := &GetUserDepositsUseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
