// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	reports "github.com/rsksmart/liquidity-provider-server/internal/usecases/reports"

	time "time"
)

// GetSummariesReportUseCaseMock is an autogenerated mock type for the GetSummariesReportUseCase type
type GetSummariesReportUseCaseMock struct {
	mock.Mock
}

type GetSummariesReportUseCaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *GetSummariesReportUseCaseMock) EXPECT() *GetSummariesReportUseCaseMock_Expecter {
	return &GetSummariesReportUseCaseMock_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, startDate, endDate
func (_m *GetSummariesReportUseCaseMock) Run(ctx context.Context, startDate time.Time, endDate time.Time) (reports.SummaryResult, error) {
	ret := _m.Called(ctx, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 reports.SummaryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (reports.SummaryResult, error)); ok {
		return rf(ctx, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) reports.SummaryResult); ok {
		r0 = rf(ctx, startDate, endDate)
	} else {
		r0 = ret.Get(0).(reports.SummaryResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSummariesReportUseCaseMock_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type GetSummariesReportUseCaseMock_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - startDate time.Time
//   - endDate time.Time
func (_e *GetSummariesReportUseCaseMock_Expecter) Run(ctx interface{}, startDate interface{}, endDate interface{}) *GetSummariesReportUseCaseMock_Run_Call {
	return &GetSummariesReportUseCaseMock_Run_Call{Call: _e.mock.On("Run", ctx, startDate, endDate)}
}

func (_c *GetSummariesReportUseCaseMock_Run_Call) Run(run func(ctx context.Context, startDate time.Time, endDate time.Time)) *GetSummariesReportUseCaseMock_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *GetSummariesReportUseCaseMock_Run_Call) Return(_a0 reports.SummaryResult, _a1 error) *GetSummariesReportUseCaseMock_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetSummariesReportUseCaseMock_Run_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) (reports.SummaryResult, error)) *GetSummariesReportUseCaseMock_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetSummariesReportUseCaseMock creates a new instance of GetSummariesReportUseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetSummariesReportUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetSummariesReportUseCaseMock {
	mock := &GetSummariesReportUseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
