// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	usecases "github.com/rsksmart/liquidity-provider-server/internal/usecases"
)

// HealthUseCaseMock is an autogenerated mock type for the HealthUseCase type
type HealthUseCaseMock struct {
	mock.Mock
}

type HealthUseCaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthUseCaseMock) EXPECT() *HealthUseCaseMock_Expecter {
	return &HealthUseCaseMock_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx
func (_m *HealthUseCaseMock) Run(ctx context.Context) usecases.HealthStatus {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 usecases.HealthStatus
	if rf, ok := ret.Get(0).(func(context.Context) usecases.HealthStatus); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(usecases.HealthStatus)
	}

	return r0
}

// HealthUseCaseMock_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type HealthUseCaseMock_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HealthUseCaseMock_Expecter) Run(ctx interface{}) *HealthUseCaseMock_Run_Call {
	return &HealthUseCaseMock_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *HealthUseCaseMock_Run_Call) Run(run func(ctx context.Context)) *HealthUseCaseMock_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HealthUseCaseMock_Run_Call) Return(_a0 usecases.HealthStatus) *HealthUseCaseMock_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HealthUseCaseMock_Run_Call) RunAndReturn(run func(context.Context) usecases.HealthStatus) *HealthUseCaseMock_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewHealthUseCaseMock creates a new instance of HealthUseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthUseCaseMock {
	mock := &HealthUseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
