// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	liquidity_provider "github.com/rsksmart/liquidity-provider-server/internal/entities/liquidity_provider"

	mock "github.com/stretchr/testify/mock"
)

// LoginUseCaseMock is an autogenerated mock type for the LoginUseCase type
type LoginUseCaseMock struct {
	mock.Mock
}

type LoginUseCaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LoginUseCaseMock) EXPECT() *LoginUseCaseMock_Expecter {
	return &LoginUseCaseMock_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, credentials
func (_m *LoginUseCaseMock) Run(ctx context.Context, credentials liquidity_provider.Credentials) error {
	ret := _m.Called(ctx, credentials)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, liquidity_provider.Credentials) error); ok {
		r0 = rf(ctx, credentials)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoginUseCaseMock_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type LoginUseCaseMock_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - credentials liquidity_provider.Credentials
func (_e *LoginUseCaseMock_Expecter) Run(ctx interface{}, credentials interface{}) *LoginUseCaseMock_Run_Call {
	return &LoginUseCaseMock_Run_Call{Call: _e.mock.On("Run", ctx, credentials)}
}

func (_c *LoginUseCaseMock_Run_Call) Run(run func(ctx context.Context, credentials liquidity_provider.Credentials)) *LoginUseCaseMock_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(liquidity_provider.Credentials))
	})
	return _c
}

func (_c *LoginUseCaseMock_Run_Call) Return(_a0 error) *LoginUseCaseMock_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoginUseCaseMock_Run_Call) RunAndReturn(run func(context.Context, liquidity_provider.Credentials) error) *LoginUseCaseMock_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoginUseCaseMock creates a new instance of LoginUseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginUseCaseMock {
	mock := &LoginUseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
