// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	blockchain "github.com/rsksmart/liquidity-provider-server/internal/entities/blockchain"
	mock "github.com/stretchr/testify/mock"
)

// PausableMock is an autogenerated mock type for the Pausable type
type PausableMock struct {
	mock.Mock
}

type PausableMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PausableMock) EXPECT() *PausableMock_Expecter {
	return &PausableMock_Expecter{mock: &_m.Mock}
}

// PausedStatus provides a mock function with no fields
func (_m *PausableMock) PausedStatus() (blockchain.PauseStatus, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PausedStatus")
	}

	var r0 blockchain.PauseStatus
	var r1 error
	if rf, ok := ret.Get(0).(func() (blockchain.PauseStatus, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() blockchain.PauseStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(blockchain.PauseStatus)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PausableMock_PausedStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PausedStatus'
type PausableMock_PausedStatus_Call struct {
	*mock.Call
}

// PausedStatus is a helper method to define mock.On call
func (_e *PausableMock_Expecter) PausedStatus() *PausableMock_PausedStatus_Call {
	return &PausableMock_PausedStatus_Call{Call: _e.mock.On("PausedStatus")}
}

func (_c *PausableMock_PausedStatus_Call) Run(run func()) *PausableMock_PausedStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PausableMock_PausedStatus_Call) Return(_a0 blockchain.PauseStatus, _a1 error) *PausableMock_PausedStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PausableMock_PausedStatus_Call) RunAndReturn(run func() (blockchain.PauseStatus, error)) *PausableMock_PausedStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewPausableMock creates a new instance of PausableMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPausableMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PausableMock {
	mock := &PausableMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
