// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	blockchain "github.com/rsksmart/liquidity-provider-server/internal/entities/blockchain"
	mock "github.com/stretchr/testify/mock"
)

// PauseRegistryContractMock is an autogenerated mock type for the PauseRegistryContract type
type PauseRegistryContractMock struct {
	mock.Mock
}

type PauseRegistryContractMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PauseRegistryContractMock) EXPECT() *PauseRegistryContractMock_Expecter {
	return &PauseRegistryContractMock_Expecter{mock: &_m.Mock}
}

// GetAddress provides a mock function with no fields
func (_m *PauseRegistryContractMock) GetAddress() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAddress")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PauseRegistryContractMock_GetAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddress'
type PauseRegistryContractMock_GetAddress_Call struct {
	*mock.Call
}

// GetAddress is a helper method to define mock.On call
func (_e *PauseRegistryContractMock_Expecter) GetAddress() *PauseRegistryContractMock_GetAddress_Call {
	return &PauseRegistryContractMock_GetAddress_Call{Call: _e.mock.On("GetAddress")}
}

func (_c *PauseRegistryContractMock_GetAddress_Call) Run(run func()) *PauseRegistryContractMock_GetAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PauseRegistryContractMock_GetAddress_Call) Return(_a0 string) *PauseRegistryContractMock_GetAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PauseRegistryContractMock_GetAddress_Call) RunAndReturn(run func() string) *PauseRegistryContractMock_GetAddress_Call {
	_c.Call.Return(run)
	return _c
}

// PauseLevel provides a mock function with no fields
func (_m *PauseRegistryContractMock) PauseLevel() (uint8, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PauseLevel")
	}

	var r0 uint8
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint8, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint8); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint8)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PauseRegistryContractMock_PauseLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseLevel'
type PauseRegistryContractMock_PauseLevel_Call struct {
	*mock.Call
}

// PauseLevel is a helper method to define mock.On call
func (_e *PauseRegistryContractMock_Expecter) PauseLevel() *PauseRegistryContractMock_PauseLevel_Call {
	return &PauseRegistryContractMock_PauseLevel_Call{Call: _e.mock.On("PauseLevel")}
}

func (_c *PauseRegistryContractMock_PauseLevel_Call) Run(run func()) *PauseRegistryContractMock_PauseLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PauseRegistryContractMock_PauseLevel_Call) Return(_a0 uint8, _a1 error) *PauseRegistryContractMock_PauseLevel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PauseRegistryContractMock_PauseLevel_Call) RunAndReturn(run func() (uint8, error)) *PauseRegistryContractMock_PauseLevel_Call {
	_c.Call.Return(run)
	return _c
}

// PauseStatus provides a mock function with no fields
func (_m *PauseRegistryContractMock) PauseStatus() (blockchain.PauseStatus, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PauseStatus")
	}

	var r0 blockchain.PauseStatus
	var r1 error
	if rf, ok := ret.Get(0).(func() (blockchain.PauseStatus, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() blockchain.PauseStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(blockchain.PauseStatus)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PauseRegistryContractMock_PauseStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseStatus'
type PauseRegistryContractMock_PauseStatus_Call struct {
	*mock.Call
}

// PauseStatus is a helper method to define mock.On call
func (_e *PauseRegistryContractMock_Expecter) PauseStatus() *PauseRegistryContractMock_PauseStatus_Call {
	return &PauseRegistryContractMock_PauseStatus_Call{Call: _e.mock.On("PauseStatus")}
}

func (_c *PauseRegistryContractMock_PauseStatus_Call) Run(run func()) *PauseRegistryContractMock_PauseStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PauseRegistryContractMock_PauseStatus_Call) Return(_a0 blockchain.PauseStatus, _a1 error) *PauseRegistryContractMock_PauseStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PauseRegistryContractMock_PauseStatus_Call) RunAndReturn(run func() (blockchain.PauseStatus, error)) *PauseRegistryContractMock_PauseStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewPauseRegistryContractMock creates a new instance of PauseRegistryContractMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPauseRegistryContractMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PauseRegistryContractMock {
	mock := &PauseRegistryContractMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
