// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	rootstock "github.com/rsksmart/liquidity-provider-server/internal/entities/rootstock"
	mock "github.com/stretchr/testify/mock"
)

// PegInAddressRegistryWatchRepositoryMock is an autogenerated mock type for the PegInAddressRegistryWatchRepository type
type PegInAddressRegistryWatchRepositoryMock struct {
	mock.Mock
}

type PegInAddressRegistryWatchRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PegInAddressRegistryWatchRepositoryMock) EXPECT() *PegInAddressRegistryWatchRepositoryMock_Expecter {
	return &PegInAddressRegistryWatchRepositoryMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, rskAddress
func (_m *PegInAddressRegistryWatchRepositoryMock) Get(ctx context.Context, rskAddress string) (*rootstock.PegInAddressRegistryWatch, error) {
	ret := _m.Called(ctx, rskAddress)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *rootstock.PegInAddressRegistryWatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*rootstock.PegInAddressRegistryWatch, error)); ok {
		return rf(ctx, rskAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *rootstock.PegInAddressRegistryWatch); ok {
		r0 = rf(ctx, rskAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rootstock.PegInAddressRegistryWatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rskAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegInAddressRegistryWatchRepositoryMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PegInAddressRegistryWatchRepositoryMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - rskAddress string
func (_e *PegInAddressRegistryWatchRepositoryMock_Expecter) Get(ctx interface{}, rskAddress interface{}) *PegInAddressRegistryWatchRepositoryMock_Get_Call {
	return &PegInAddressRegistryWatchRepositoryMock_Get_Call{Call: _e.mock.On("Get", ctx, rskAddress)}
}

func (_c *PegInAddressRegistryWatchRepositoryMock_Get_Call) Run(run func(ctx context.Context, rskAddress string)) *PegInAddressRegistryWatchRepositoryMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PegInAddressRegistryWatchRepositoryMock_Get_Call) Return(_a0 *rootstock.PegInAddressRegistryWatch, _a1 error) *PegInAddressRegistryWatchRepositoryMock_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegInAddressRegistryWatchRepositoryMock_Get_Call) RunAndReturn(run func(context.Context, string) (*rootstock.PegInAddressRegistryWatch, error)) *PegInAddressRegistryWatchRepositoryMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *PegInAddressRegistryWatchRepositoryMock) List(ctx context.Context) ([]rootstock.PegInAddressRegistryWatch, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []rootstock.PegInAddressRegistryWatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]rootstock.PegInAddressRegistryWatch, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []rootstock.PegInAddressRegistryWatch); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rootstock.PegInAddressRegistryWatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegInAddressRegistryWatchRepositoryMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PegInAddressRegistryWatchRepositoryMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PegInAddressRegistryWatchRepositoryMock_Expecter) List(ctx interface{}) *PegInAddressRegistryWatchRepositoryMock_List_Call {
	return &PegInAddressRegistryWatchRepositoryMock_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *PegInAddressRegistryWatchRepositoryMock_List_Call) Run(run func(ctx context.Context)) *PegInAddressRegistryWatchRepositoryMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PegInAddressRegistryWatchRepositoryMock_List_Call) Return(_a0 []rootstock.PegInAddressRegistryWatch, _a1 error) *PegInAddressRegistryWatchRepositoryMock_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegInAddressRegistryWatchRepositoryMock_List_Call) RunAndReturn(run func(context.Context) ([]rootstock.PegInAddressRegistryWatch, error)) *PegInAddressRegistryWatchRepositoryMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, watch
func (_m *PegInAddressRegistryWatchRepositoryMock) Update(ctx context.Context, watch rootstock.PegInAddressRegistryWatch) error {
	ret := _m.Called(ctx, watch)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rootstock.PegInAddressRegistryWatch) error); ok {
		r0 = rf(ctx, watch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegInAddressRegistryWatchRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PegInAddressRegistryWatchRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - watch rootstock.PegInAddressRegistryWatch
func (_e *PegInAddressRegistryWatchRepositoryMock_Expecter) Update(ctx interface{}, watch interface{}) *PegInAddressRegistryWatchRepositoryMock_Update_Call {
	return &PegInAddressRegistryWatchRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, watch)}
}

func (_c *PegInAddressRegistryWatchRepositoryMock_Update_Call) Run(run func(ctx context.Context, watch rootstock.PegInAddressRegistryWatch)) *PegInAddressRegistryWatchRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rootstock.PegInAddressRegistryWatch))
	})
	return _c
}

func (_c *PegInAddressRegistryWatchRepositoryMock_Update_Call) Return(_a0 error) *PegInAddressRegistryWatchRepositoryMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegInAddressRegistryWatchRepositoryMock_Update_Call) RunAndReturn(run func(context.Context, rootstock.PegInAddressRegistryWatch) error) *PegInAddressRegistryWatchRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, watch
func (_m *PegInAddressRegistryWatchRepositoryMock) Upsert(ctx context.Context, watch rootstock.PegInAddressRegistryWatch) error {
	ret := _m.Called(ctx, watch)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rootstock.PegInAddressRegistryWatch) error); ok {
		r0 = rf(ctx, watch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegInAddressRegistryWatchRepositoryMock_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type PegInAddressRegistryWatchRepositoryMock_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - watch rootstock.PegInAddressRegistryWatch
func (_e *PegInAddressRegistryWatchRepositoryMock_Expecter) Upsert(ctx interface{}, watch interface{}) *PegInAddressRegistryWatchRepositoryMock_Upsert_Call {
	return &PegInAddressRegistryWatchRepositoryMock_Upsert_Call{Call: _e.mock.On("Upsert", ctx, watch)}
}

func (_c *PegInAddressRegistryWatchRepositoryMock_Upsert_Call) Run(run func(ctx context.Context, watch rootstock.PegInAddressRegistryWatch)) *PegInAddressRegistryWatchRepositoryMock_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rootstock.PegInAddressRegistryWatch))
	})
	return _c
}

func (_c *PegInAddressRegistryWatchRepositoryMock_Upsert_Call) Return(_a0 error) *PegInAddressRegistryWatchRepositoryMock_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegInAddressRegistryWatchRepositoryMock_Upsert_Call) RunAndReturn(run func(context.Context, rootstock.PegInAddressRegistryWatch) error) *PegInAddressRegistryWatchRepositoryMock_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewPegInAddressRegistryWatchRepositoryMock creates a new instance of PegInAddressRegistryWatchRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPegInAddressRegistryWatchRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PegInAddressRegistryWatchRepositoryMock {
	mock := &PegInAddressRegistryWatchRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
