// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	rootstock "github.com/rsksmart/liquidity-provider-server/internal/entities/rootstock"
	mock "github.com/stretchr/testify/mock"
)

// PegInWatchRepositoryMock is an autogenerated mock type for the PegInWatchRepository type
type PegInWatchRepositoryMock struct {
	mock.Mock
}

type PegInWatchRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PegInWatchRepositoryMock) EXPECT() *PegInWatchRepositoryMock_Expecter {
	return &PegInWatchRepositoryMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, rskAddress
func (_m *PegInWatchRepositoryMock) Get(ctx context.Context, rskAddress string) (*rootstock.PegInWatch, error) {
	ret := _m.Called(ctx, rskAddress)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *rootstock.PegInWatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*rootstock.PegInWatch, error)); ok {
		return rf(ctx, rskAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *rootstock.PegInWatch); ok {
		r0 = rf(ctx, rskAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rootstock.PegInWatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rskAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegInWatchRepositoryMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PegInWatchRepositoryMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - rskAddress string
func (_e *PegInWatchRepositoryMock_Expecter) Get(ctx interface{}, rskAddress interface{}) *PegInWatchRepositoryMock_Get_Call {
	return &PegInWatchRepositoryMock_Get_Call{Call: _e.mock.On("Get", ctx, rskAddress)}
}

func (_c *PegInWatchRepositoryMock_Get_Call) Run(run func(ctx context.Context, rskAddress string)) *PegInWatchRepositoryMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PegInWatchRepositoryMock_Get_Call) Return(_a0 *rootstock.PegInWatch, _a1 error) *PegInWatchRepositoryMock_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegInWatchRepositoryMock_Get_Call) RunAndReturn(run func(context.Context, string) (*rootstock.PegInWatch, error)) *PegInWatchRepositoryMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *PegInWatchRepositoryMock) List(ctx context.Context) ([]rootstock.PegInWatch, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []rootstock.PegInWatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]rootstock.PegInWatch, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []rootstock.PegInWatch); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rootstock.PegInWatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegInWatchRepositoryMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PegInWatchRepositoryMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PegInWatchRepositoryMock_Expecter) List(ctx interface{}) *PegInWatchRepositoryMock_List_Call {
	return &PegInWatchRepositoryMock_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *PegInWatchRepositoryMock_List_Call) Run(run func(ctx context.Context)) *PegInWatchRepositoryMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PegInWatchRepositoryMock_List_Call) Return(_a0 []rootstock.PegInWatch, _a1 error) *PegInWatchRepositoryMock_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegInWatchRepositoryMock_List_Call) RunAndReturn(run func(context.Context) ([]rootstock.PegInWatch, error)) *PegInWatchRepositoryMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, watch
func (_m *PegInWatchRepositoryMock) Update(ctx context.Context, watch rootstock.PegInWatch) error {
	ret := _m.Called(ctx, watch)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rootstock.PegInWatch) error); ok {
		r0 = rf(ctx, watch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegInWatchRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PegInWatchRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - watch rootstock.PegInWatch
func (_e *PegInWatchRepositoryMock_Expecter) Update(ctx interface{}, watch interface{}) *PegInWatchRepositoryMock_Update_Call {
	return &PegInWatchRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, watch)}
}

func (_c *PegInWatchRepositoryMock_Update_Call) Run(run func(ctx context.Context, watch rootstock.PegInWatch)) *PegInWatchRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rootstock.PegInWatch))
	})
	return _c
}

func (_c *PegInWatchRepositoryMock_Update_Call) Return(_a0 error) *PegInWatchRepositoryMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegInWatchRepositoryMock_Update_Call) RunAndReturn(run func(context.Context, rootstock.PegInWatch) error) *PegInWatchRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, watch
func (_m *PegInWatchRepositoryMock) Upsert(ctx context.Context, watch rootstock.PegInWatch) error {
	ret := _m.Called(ctx, watch)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rootstock.PegInWatch) error); ok {
		r0 = rf(ctx, watch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegInWatchRepositoryMock_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type PegInWatchRepositoryMock_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - watch rootstock.PegInWatch
func (_e *PegInWatchRepositoryMock_Expecter) Upsert(ctx interface{}, watch interface{}) *PegInWatchRepositoryMock_Upsert_Call {
	return &PegInWatchRepositoryMock_Upsert_Call{Call: _e.mock.On("Upsert", ctx, watch)}
}

func (_c *PegInWatchRepositoryMock_Upsert_Call) Run(run func(ctx context.Context, watch rootstock.PegInWatch)) *PegInWatchRepositoryMock_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rootstock.PegInWatch))
	})
	return _c
}

func (_c *PegInWatchRepositoryMock_Upsert_Call) Return(_a0 error) *PegInWatchRepositoryMock_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegInWatchRepositoryMock_Upsert_Call) RunAndReturn(run func(context.Context, rootstock.PegInWatch) error) *PegInWatchRepositoryMock_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewPegInWatchRepositoryMock creates a new instance of PegInWatchRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPegInWatchRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PegInWatchRepositoryMock {
	mock := &PegInWatchRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
