// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	rootstock "github.com/rsksmart/liquidity-provider-server/internal/entities/rootstock"
	mock "github.com/stretchr/testify/mock"
)

// PegInClaimRunnerMock is an autogenerated mock type for the PegInClaimRunner type
type PegInClaimRunnerMock struct {
	mock.Mock
}

type PegInClaimRunnerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PegInClaimRunnerMock) EXPECT() *PegInClaimRunnerMock_Expecter {
	return &PegInClaimRunnerMock_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, entry, depositTxID
func (_m *PegInClaimRunnerMock) Run(ctx context.Context, entry rootstock.PegInWatch, depositTxID string) error {
	ret := _m.Called(ctx, entry, depositTxID)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rootstock.PegInWatch, string) error); ok {
		r0 = rf(ctx, entry, depositTxID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegInClaimRunnerMock_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type PegInClaimRunnerMock_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - entry rootstock.PegInWatch
//   - depositTxID string
func (_e *PegInClaimRunnerMock_Expecter) Run(ctx interface{}, entry interface{}, depositTxID interface{}) *PegInClaimRunnerMock_Run_Call {
	return &PegInClaimRunnerMock_Run_Call{Call: _e.mock.On("Run", ctx, entry, depositTxID)}
}

func (_c *PegInClaimRunnerMock_Run_Call) Run(run func(ctx context.Context, entry rootstock.PegInWatch, depositTxID string)) *PegInClaimRunnerMock_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rootstock.PegInWatch), args[2].(string))
	})
	return _c
}

func (_c *PegInClaimRunnerMock_Run_Call) Return(_a0 error) *PegInClaimRunnerMock_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegInClaimRunnerMock_Run_Call) RunAndReturn(run func(context.Context, rootstock.PegInWatch, string) error) *PegInClaimRunnerMock_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewPegInClaimRunnerMock creates a new instance of PegInClaimRunnerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPegInClaimRunnerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PegInClaimRunnerMock {
	mock := &PegInClaimRunnerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
