// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	rootstock "github.com/rsksmart/liquidity-provider-server/internal/entities/rootstock"
	mock "github.com/stretchr/testify/mock"
)

// PegInClaimsGetterMock is an autogenerated mock type for the PegInClaimsGetter type
type PegInClaimsGetterMock struct {
	mock.Mock
}

type PegInClaimsGetterMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PegInClaimsGetterMock) EXPECT() *PegInClaimsGetterMock_Expecter {
	return &PegInClaimsGetterMock_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, states
func (_m *PegInClaimsGetterMock) Run(ctx context.Context, states ...rootstock.PegInClaimState) ([]rootstock.PegInClaim, error) {
	_va := make([]interface{}, len(states))
	for _i := range states {
		_va[_i] = states[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 []rootstock.PegInClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...rootstock.PegInClaimState) ([]rootstock.PegInClaim, error)); ok {
		return rf(ctx, states...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...rootstock.PegInClaimState) []rootstock.PegInClaim); ok {
		r0 = rf(ctx, states...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rootstock.PegInClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...rootstock.PegInClaimState) error); ok {
		r1 = rf(ctx, states...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegInClaimsGetterMock_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type PegInClaimsGetterMock_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - states ...rootstock.PegInClaimState
func (_e *PegInClaimsGetterMock_Expecter) Run(ctx interface{}, states ...interface{}) *PegInClaimsGetterMock_Run_Call {
	return &PegInClaimsGetterMock_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{ctx}, states...)...)}
}

func (_c *PegInClaimsGetterMock_Run_Call) Run(run func(ctx context.Context, states ...rootstock.PegInClaimState)) *PegInClaimsGetterMock_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]rootstock.PegInClaimState, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(rootstock.PegInClaimState)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *PegInClaimsGetterMock_Run_Call) Return(_a0 []rootstock.PegInClaim, _a1 error) *PegInClaimsGetterMock_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegInClaimsGetterMock_Run_Call) RunAndReturn(run func(context.Context, ...rootstock.PegInClaimState) ([]rootstock.PegInClaim, error)) *PegInClaimsGetterMock_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewPegInClaimsGetterMock creates a new instance of PegInClaimsGetterMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPegInClaimsGetterMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PegInClaimsGetterMock {
	mock := &PegInClaimsGetterMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
