// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	rootstock "github.com/rsksmart/liquidity-provider-server/internal/entities/rootstock"
	mock "github.com/stretchr/testify/mock"
)

// PegInClaimRepositoryMock is an autogenerated mock type for the PegInClaimRepository type
type PegInClaimRepositoryMock struct {
	mock.Mock
}

type PegInClaimRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PegInClaimRepositoryMock) EXPECT() *PegInClaimRepositoryMock_Expecter {
	return &PegInClaimRepositoryMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, rskAddress, depositTxID
func (_m *PegInClaimRepositoryMock) Get(ctx context.Context, rskAddress string, depositTxID string) (*rootstock.PegInClaim, error) {
	ret := _m.Called(ctx, rskAddress, depositTxID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *rootstock.PegInClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*rootstock.PegInClaim, error)); ok {
		return rf(ctx, rskAddress, depositTxID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *rootstock.PegInClaim); ok {
		r0 = rf(ctx, rskAddress, depositTxID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rootstock.PegInClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, rskAddress, depositTxID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegInClaimRepositoryMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PegInClaimRepositoryMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - rskAddress string
//   - depositTxID string
func (_e *PegInClaimRepositoryMock_Expecter) Get(ctx interface{}, rskAddress interface{}, depositTxID interface{}) *PegInClaimRepositoryMock_Get_Call {
	return &PegInClaimRepositoryMock_Get_Call{Call: _e.mock.On("Get", ctx, rskAddress, depositTxID)}
}

func (_c *PegInClaimRepositoryMock_Get_Call) Run(run func(ctx context.Context, rskAddress string, depositTxID string)) *PegInClaimRepositoryMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *PegInClaimRepositoryMock_Get_Call) Return(_a0 *rootstock.PegInClaim, _a1 error) *PegInClaimRepositoryMock_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegInClaimRepositoryMock_Get_Call) RunAndReturn(run func(context.Context, string, string) (*rootstock.PegInClaim, error)) *PegInClaimRepositoryMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *PegInClaimRepositoryMock) Insert(_a0 context.Context, _a1 rootstock.PegInClaim) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rootstock.PegInClaim) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegInClaimRepositoryMock_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type PegInClaimRepositoryMock_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 rootstock.PegInClaim
func (_e *PegInClaimRepositoryMock_Expecter) Insert(_a0 interface{}, _a1 interface{}) *PegInClaimRepositoryMock_Insert_Call {
	return &PegInClaimRepositoryMock_Insert_Call{Call: _e.mock.On("Insert", _a0, _a1)}
}

func (_c *PegInClaimRepositoryMock_Insert_Call) Run(run func(_a0 context.Context, _a1 rootstock.PegInClaim)) *PegInClaimRepositoryMock_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rootstock.PegInClaim))
	})
	return _c
}

func (_c *PegInClaimRepositoryMock_Insert_Call) Return(_a0 error) *PegInClaimRepositoryMock_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegInClaimRepositoryMock_Insert_Call) RunAndReturn(run func(context.Context, rootstock.PegInClaim) error) *PegInClaimRepositoryMock_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// ListByStates provides a mock function with given fields: ctx, states
func (_m *PegInClaimRepositoryMock) ListByStates(ctx context.Context, states ...rootstock.PegInClaimState) ([]rootstock.PegInClaim, error) {
	_va := make([]interface{}, len(states))
	for _i := range states {
		_va[_i] = states[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListByStates")
	}

	var r0 []rootstock.PegInClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...rootstock.PegInClaimState) ([]rootstock.PegInClaim, error)); ok {
		return rf(ctx, states...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...rootstock.PegInClaimState) []rootstock.PegInClaim); ok {
		r0 = rf(ctx, states...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rootstock.PegInClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...rootstock.PegInClaimState) error); ok {
		r1 = rf(ctx, states...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegInClaimRepositoryMock_ListByStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByStates'
type PegInClaimRepositoryMock_ListByStates_Call struct {
	*mock.Call
}

// ListByStates is a helper method to define mock.On call
//   - ctx context.Context
//   - states ...rootstock.PegInClaimState
func (_e *PegInClaimRepositoryMock_Expecter) ListByStates(ctx interface{}, states ...interface{}) *PegInClaimRepositoryMock_ListByStates_Call {
	return &PegInClaimRepositoryMock_ListByStates_Call{Call: _e.mock.On("ListByStates",
		append([]interface{}{ctx}, states...)...)}
}

func (_c *PegInClaimRepositoryMock_ListByStates_Call) Run(run func(ctx context.Context, states ...rootstock.PegInClaimState)) *PegInClaimRepositoryMock_ListByStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]rootstock.PegInClaimState, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(rootstock.PegInClaimState)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *PegInClaimRepositoryMock_ListByStates_Call) Return(_a0 []rootstock.PegInClaim, _a1 error) *PegInClaimRepositoryMock_ListByStates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegInClaimRepositoryMock_ListByStates_Call) RunAndReturn(run func(context.Context, ...rootstock.PegInClaimState) ([]rootstock.PegInClaim, error)) *PegInClaimRepositoryMock_ListByStates_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *PegInClaimRepositoryMock) Update(_a0 context.Context, _a1 rootstock.PegInClaim) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rootstock.PegInClaim) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegInClaimRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PegInClaimRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 rootstock.PegInClaim
func (_e *PegInClaimRepositoryMock_Expecter) Update(_a0 interface{}, _a1 interface{}) *PegInClaimRepositoryMock_Update_Call {
	return &PegInClaimRepositoryMock_Update_Call{Call: _e.mock.On("Update", _a0, _a1)}
}

func (_c *PegInClaimRepositoryMock_Update_Call) Run(run func(_a0 context.Context, _a1 rootstock.PegInClaim)) *PegInClaimRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rootstock.PegInClaim))
	})
	return _c
}

func (_c *PegInClaimRepositoryMock_Update_Call) Return(_a0 error) *PegInClaimRepositoryMock_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegInClaimRepositoryMock_Update_Call) RunAndReturn(run func(context.Context, rootstock.PegInClaim) error) *PegInClaimRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewPegInClaimRepositoryMock creates a new instance of PegInClaimRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPegInClaimRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PegInClaimRepositoryMock {
	mock := &PegInClaimRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
