// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	rootstock "github.com/rsksmart/liquidity-provider-server/internal/entities/rootstock"
	mock "github.com/stretchr/testify/mock"
)

// PegInClaimSettlerMock is an autogenerated mock type for the PegInClaimSettler type
type PegInClaimSettlerMock struct {
	mock.Mock
}

type PegInClaimSettlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PegInClaimSettlerMock) EXPECT() *PegInClaimSettlerMock_Expecter {
	return &PegInClaimSettlerMock_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, claim
func (_m *PegInClaimSettlerMock) Run(ctx context.Context, claim rootstock.PegInClaim) error {
	ret := _m.Called(ctx, claim)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rootstock.PegInClaim) error); ok {
		r0 = rf(ctx, claim)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegInClaimSettlerMock_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type PegInClaimSettlerMock_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - claim rootstock.PegInClaim
func (_e *PegInClaimSettlerMock_Expecter) Run(ctx interface{}, claim interface{}) *PegInClaimSettlerMock_Run_Call {
	return &PegInClaimSettlerMock_Run_Call{Call: _e.mock.On("Run", ctx, claim)}
}

func (_c *PegInClaimSettlerMock_Run_Call) Run(run func(ctx context.Context, claim rootstock.PegInClaim)) *PegInClaimSettlerMock_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rootstock.PegInClaim))
	})
	return _c
}

func (_c *PegInClaimSettlerMock_Run_Call) Return(_a0 error) *PegInClaimSettlerMock_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegInClaimSettlerMock_Run_Call) RunAndReturn(run func(context.Context, rootstock.PegInClaim) error) *PegInClaimSettlerMock_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewPegInClaimSettlerMock creates a new instance of PegInClaimSettlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPegInClaimSettlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PegInClaimSettlerMock {
	mock := &PegInClaimSettlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
