// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	quote "github.com/rsksmart/liquidity-provider-server/internal/entities/quote"
	mock "github.com/stretchr/testify/mock"

	rootstock "github.com/rsksmart/liquidity-provider-server/internal/entities/rootstock"

	time "time"
)

// PegoutQuoteRepositoryMock is an autogenerated mock type for the PegoutQuoteRepository type
type PegoutQuoteRepositoryMock struct {
	mock.Mock
}

type PegoutQuoteRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PegoutQuoteRepositoryMock) EXPECT() *PegoutQuoteRepositoryMock_Expecter {
	return &PegoutQuoteRepositoryMock_Expecter{mock: &_m.Mock}
}

// DeleteQuotes provides a mock function with given fields: ctx, quotes
func (_m *PegoutQuoteRepositoryMock) DeleteQuotes(ctx context.Context, quotes []string) (uint, error) {
	ret := _m.Called(ctx, quotes)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuotes")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (uint, error)); ok {
		return rf(ctx, quotes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) uint); ok {
		r0 = rf(ctx, quotes)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, quotes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegoutQuoteRepositoryMock_DeleteQuotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQuotes'
type PegoutQuoteRepositoryMock_DeleteQuotes_Call struct {
	*mock.Call
}

// DeleteQuotes is a helper method to define mock.On call
//   - ctx context.Context
//   - quotes []string
func (_e *PegoutQuoteRepositoryMock_Expecter) DeleteQuotes(ctx interface{}, quotes interface{}) *PegoutQuoteRepositoryMock_DeleteQuotes_Call {
	return &PegoutQuoteRepositoryMock_DeleteQuotes_Call{Call: _e.mock.On("DeleteQuotes", ctx, quotes)}
}

func (_c *PegoutQuoteRepositoryMock_DeleteQuotes_Call) Run(run func(ctx context.Context, quotes []string)) *PegoutQuoteRepositoryMock_DeleteQuotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_DeleteQuotes_Call) Return(_a0 uint, _a1 error) *PegoutQuoteRepositoryMock_DeleteQuotes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_DeleteQuotes_Call) RunAndReturn(run func(context.Context, []string) (uint, error)) *PegoutQuoteRepositoryMock_DeleteQuotes_Call {
	_c.Call.Return(run)
	return _c
}

// GetPegoutCreationData provides a mock function with given fields: ctx, hash
func (_m *PegoutQuoteRepositoryMock) GetPegoutCreationData(ctx context.Context, hash string) quote.PegoutCreationData {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetPegoutCreationData")
	}

	var r0 quote.PegoutCreationData
	if rf, ok := ret.Get(0).(func(context.Context, string) quote.PegoutCreationData); ok {
		r0 = rf(ctx, hash)
	} else {
		r0 = ret.Get(0).(quote.PegoutCreationData)
	}

	return r0
}

// PegoutQuoteRepositoryMock_GetPegoutCreationData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPegoutCreationData'
type PegoutQuoteRepositoryMock_GetPegoutCreationData_Call struct {
	*mock.Call
}

// GetPegoutCreationData is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *PegoutQuoteRepositoryMock_Expecter) GetPegoutCreationData(ctx interface{}, hash interface{}) *PegoutQuoteRepositoryMock_GetPegoutCreationData_Call {
	return &PegoutQuoteRepositoryMock_GetPegoutCreationData_Call{Call: _e.mock.On("GetPegoutCreationData", ctx, hash)}
}

func (_c *PegoutQuoteRepositoryMock_GetPegoutCreationData_Call) Run(run func(ctx context.Context, hash string)) *PegoutQuoteRepositoryMock_GetPegoutCreationData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetPegoutCreationData_Call) Return(_a0 quote.PegoutCreationData) *PegoutQuoteRepositoryMock_GetPegoutCreationData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetPegoutCreationData_Call) RunAndReturn(run func(context.Context, string) quote.PegoutCreationData) *PegoutQuoteRepositoryMock_GetPegoutCreationData_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuote provides a mock function with given fields: ctx, hash
func (_m *PegoutQuoteRepositoryMock) GetQuote(ctx context.Context, hash string) (*quote.PegoutQuote, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetQuote")
	}

	var r0 *quote.PegoutQuote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*quote.PegoutQuote, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *quote.PegoutQuote); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*quote.PegoutQuote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegoutQuoteRepositoryMock_GetQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuote'
type PegoutQuoteRepositoryMock_GetQuote_Call struct {
	*mock.Call
}

// GetQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *PegoutQuoteRepositoryMock_Expecter) GetQuote(ctx interface{}, hash interface{}) *PegoutQuoteRepositoryMock_GetQuote_Call {
	return &PegoutQuoteRepositoryMock_GetQuote_Call{Call: _e.mock.On("GetQuote", ctx, hash)}
}

func (_c *PegoutQuoteRepositoryMock_GetQuote_Call) Run(run func(ctx context.Context, hash string)) *PegoutQuoteRepositoryMock_GetQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetQuote_Call) Return(_a0 *quote.PegoutQuote, _a1 error) *PegoutQuoteRepositoryMock_GetQuote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetQuote_Call) RunAndReturn(run func(context.Context, string) (*quote.PegoutQuote, error)) *PegoutQuoteRepositoryMock_GetQuote_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuotesByHashesAndDate provides a mock function with given fields: ctx, hashes, startDate, endDate
func (_m *PegoutQuoteRepositoryMock) GetQuotesByHashesAndDate(ctx context.Context, hashes []string, startDate time.Time, endDate time.Time) ([]quote.PegoutQuote, error) {
	ret := _m.Called(ctx, hashes, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotesByHashesAndDate")
	}

	var r0 []quote.PegoutQuote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time) ([]quote.PegoutQuote, error)); ok {
		return rf(ctx, hashes, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, time.Time, time.Time) []quote.PegoutQuote); ok {
		r0 = rf(ctx, hashes, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]quote.PegoutQuote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, hashes, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegoutQuoteRepositoryMock_GetQuotesByHashesAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotesByHashesAndDate'
type PegoutQuoteRepositoryMock_GetQuotesByHashesAndDate_Call struct {
	*mock.Call
}

// GetQuotesByHashesAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - hashes []string
//   - startDate time.Time
//   - endDate time.Time
func (_e *PegoutQuoteRepositoryMock_Expecter) GetQuotesByHashesAndDate(ctx interface{}, hashes interface{}, startDate interface{}, endDate interface{}) *PegoutQuoteRepositoryMock_GetQuotesByHashesAndDate_Call {
	return &PegoutQuoteRepositoryMock_GetQuotesByHashesAndDate_Call{Call: _e.mock.On("GetQuotesByHashesAndDate", ctx, hashes, startDate, endDate)}
}

func (_c *PegoutQuoteRepositoryMock_GetQuotesByHashesAndDate_Call) Run(run func(ctx context.Context, hashes []string, startDate time.Time, endDate time.Time)) *PegoutQuoteRepositoryMock_GetQuotesByHashesAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetQuotesByHashesAndDate_Call) Return(_a0 []quote.PegoutQuote, _a1 error) *PegoutQuoteRepositoryMock_GetQuotesByHashesAndDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetQuotesByHashesAndDate_Call) RunAndReturn(run func(context.Context, []string, time.Time, time.Time) ([]quote.PegoutQuote, error)) *PegoutQuoteRepositoryMock_GetQuotesByHashesAndDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuotesByState provides a mock function with given fields: ctx, states
func (_m *PegoutQuoteRepositoryMock) GetQuotesByState(ctx context.Context, states ...quote.PegoutState) ([]quote.PegoutQuote, error) {
	_va := make([]interface{}, len(states))
	for _i := range states {
		_va[_i] = states[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotesByState")
	}

	var r0 []quote.PegoutQuote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...quote.PegoutState) ([]quote.PegoutQuote, error)); ok {
		return rf(ctx, states...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...quote.PegoutState) []quote.PegoutQuote); ok {
		r0 = rf(ctx, states...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]quote.PegoutQuote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...quote.PegoutState) error); ok {
		r1 = rf(ctx, states...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegoutQuoteRepositoryMock_GetQuotesByState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotesByState'
type PegoutQuoteRepositoryMock_GetQuotesByState_Call struct {
	*mock.Call
}

// GetQuotesByState is a helper method to define mock.On call
//   - ctx context.Context
//   - states ...quote.PegoutState
func (_e *PegoutQuoteRepositoryMock_Expecter) GetQuotesByState(ctx interface{}, states ...interface{}) *PegoutQuoteRepositoryMock_GetQuotesByState_Call {
	return &PegoutQuoteRepositoryMock_GetQuotesByState_Call{Call: _e.mock.On("GetQuotesByState",
		append([]interface{}{ctx}, states...)...)}
}

func (_c *PegoutQuoteRepositoryMock_GetQuotesByState_Call) Run(run func(ctx context.Context, states ...quote.PegoutState)) *PegoutQuoteRepositoryMock_GetQuotesByState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]quote.PegoutState, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(quote.PegoutState)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetQuotesByState_Call) Return(_a0 []quote.PegoutQuote, _a1 error) *PegoutQuoteRepositoryMock_GetQuotesByState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetQuotesByState_Call) RunAndReturn(run func(context.Context, ...quote.PegoutState) ([]quote.PegoutQuote, error)) *PegoutQuoteRepositoryMock_GetQuotesByState_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuotesWithRetainedByStateAndDate provides a mock function with given fields: ctx, states, startDate, endDate
func (_m *PegoutQuoteRepositoryMock) GetQuotesWithRetainedByStateAndDate(ctx context.Context, states []quote.PegoutState, startDate time.Time, endDate time.Time) ([]quote.PegoutQuoteWithRetained, error) {
	ret := _m.Called(ctx, states, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotesWithRetainedByStateAndDate")
	}

	var r0 []quote.PegoutQuoteWithRetained
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []quote.PegoutState, time.Time, time.Time) ([]quote.PegoutQuoteWithRetained, error)); ok {
		return rf(ctx, states, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []quote.PegoutState, time.Time, time.Time) []quote.PegoutQuoteWithRetained); ok {
		r0 = rf(ctx, states, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]quote.PegoutQuoteWithRetained)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []quote.PegoutState, time.Time, time.Time) error); ok {
		r1 = rf(ctx, states, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegoutQuoteRepositoryMock_GetQuotesWithRetainedByStateAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotesWithRetainedByStateAndDate'
type PegoutQuoteRepositoryMock_GetQuotesWithRetainedByStateAndDate_Call struct {
	*mock.Call
}

// GetQuotesWithRetainedByStateAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - states []quote.PegoutState
//   - startDate time.Time
//   - endDate time.Time
func (_e *PegoutQuoteRepositoryMock_Expecter) GetQuotesWithRetainedByStateAndDate(ctx interface{}, states interface{}, startDate interface{}, endDate interface{}) *PegoutQuoteRepositoryMock_GetQuotesWithRetainedByStateAndDate_Call {
	return &PegoutQuoteRepositoryMock_GetQuotesWithRetainedByStateAndDate_Call{Call: _e.mock.On("GetQuotesWithRetainedByStateAndDate", ctx, states, startDate, endDate)}
}

func (_c *PegoutQuoteRepositoryMock_GetQuotesWithRetainedByStateAndDate_Call) Run(run func(ctx context.Context, states []quote.PegoutState, startDate time.Time, endDate time.Time)) *PegoutQuoteRepositoryMock_GetQuotesWithRetainedByStateAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]quote.PegoutState), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetQuotesWithRetainedByStateAndDate_Call) Return(_a0 []quote.PegoutQuoteWithRetained, _a1 error) *PegoutQuoteRepositoryMock_GetQuotesWithRetainedByStateAndDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetQuotesWithRetainedByStateAndDate_Call) RunAndReturn(run func(context.Context, []quote.PegoutState, time.Time, time.Time) ([]quote.PegoutQuoteWithRetained, error)) *PegoutQuoteRepositoryMock_GetQuotesWithRetainedByStateAndDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetRetainedQuote provides a mock function with given fields: ctx, hash
func (_m *PegoutQuoteRepositoryMock) GetRetainedQuote(ctx context.Context, hash string) (*quote.RetainedPegoutQuote, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetRetainedQuote")
	}

	var r0 *quote.RetainedPegoutQuote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*quote.RetainedPegoutQuote, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *quote.RetainedPegoutQuote); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*quote.RetainedPegoutQuote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegoutQuoteRepositoryMock_GetRetainedQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetainedQuote'
type PegoutQuoteRepositoryMock_GetRetainedQuote_Call struct {
	*mock.Call
}

// GetRetainedQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
func (_e *PegoutQuoteRepositoryMock_Expecter) GetRetainedQuote(ctx interface{}, hash interface{}) *PegoutQuoteRepositoryMock_GetRetainedQuote_Call {
	return &PegoutQuoteRepositoryMock_GetRetainedQuote_Call{Call: _e.mock.On("GetRetainedQuote", ctx, hash)}
}

func (_c *PegoutQuoteRepositoryMock_GetRetainedQuote_Call) Run(run func(ctx context.Context, hash string)) *PegoutQuoteRepositoryMock_GetRetainedQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetRetainedQuote_Call) Return(_a0 *quote.RetainedPegoutQuote, _a1 error) *PegoutQuoteRepositoryMock_GetRetainedQuote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetRetainedQuote_Call) RunAndReturn(run func(context.Context, string) (*quote.RetainedPegoutQuote, error)) *PegoutQuoteRepositoryMock_GetRetainedQuote_Call {
	_c.Call.Return(run)
	return _c
}

// GetRetainedQuoteByState provides a mock function with given fields: ctx, states
func (_m *PegoutQuoteRepositoryMock) GetRetainedQuoteByState(ctx context.Context, states ...quote.PegoutState) ([]quote.RetainedPegoutQuote, error) {
	_va := make([]interface{}, len(states))
	for _i := range states {
		_va[_i] = states[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetRetainedQuoteByState")
	}

	var r0 []quote.RetainedPegoutQuote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...quote.PegoutState) ([]quote.RetainedPegoutQuote, error)); ok {
		return rf(ctx, states...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...quote.PegoutState) []quote.RetainedPegoutQuote); ok {
		r0 = rf(ctx, states...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]quote.RetainedPegoutQuote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...quote.PegoutState) error); ok {
		r1 = rf(ctx, states...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegoutQuoteRepositoryMock_GetRetainedQuoteByState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetainedQuoteByState'
type PegoutQuoteRepositoryMock_GetRetainedQuoteByState_Call struct {
	*mock.Call
}

// GetRetainedQuoteByState is a helper method to define mock.On call
//   - ctx context.Context
//   - states ...quote.PegoutState
func (_e *PegoutQuoteRepositoryMock_Expecter) GetRetainedQuoteByState(ctx interface{}, states ...interface{}) *PegoutQuoteRepositoryMock_GetRetainedQuoteByState_Call {
	return &PegoutQuoteRepositoryMock_GetRetainedQuoteByState_Call{Call: _e.mock.On("GetRetainedQuoteByState",
		append([]interface{}{ctx}, states...)...)}
}

func (_c *PegoutQuoteRepositoryMock_GetRetainedQuoteByState_Call) Run(run func(ctx context.Context, states ...quote.PegoutState)) *PegoutQuoteRepositoryMock_GetRetainedQuoteByState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]quote.PegoutState, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(quote.PegoutState)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetRetainedQuoteByState_Call) Return(_a0 []quote.RetainedPegoutQuote, _a1 error) *PegoutQuoteRepositoryMock_GetRetainedQuoteByState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetRetainedQuoteByState_Call) RunAndReturn(run func(context.Context, ...quote.PegoutState) ([]quote.RetainedPegoutQuote, error)) *PegoutQuoteRepositoryMock_GetRetainedQuoteByState_Call {
	_c.Call.Return(run)
	return _c
}

// GetRetainedQuotesForAddress provides a mock function with given fields: ctx, address, states
func (_m *PegoutQuoteRepositoryMock) GetRetainedQuotesForAddress(ctx context.Context, address string, states ...quote.PegoutState) ([]quote.RetainedPegoutQuote, error) {
	_va := make([]interface{}, len(states))
	for _i := range states {
		_va[_i] = states[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, address)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetRetainedQuotesForAddress")
	}

	var r0 []quote.RetainedPegoutQuote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...quote.PegoutState) ([]quote.RetainedPegoutQuote, error)); ok {
		return rf(ctx, address, states...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...quote.PegoutState) []quote.RetainedPegoutQuote); ok {
		r0 = rf(ctx, address, states...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]quote.RetainedPegoutQuote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...quote.PegoutState) error); ok {
		r1 = rf(ctx, address, states...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegoutQuoteRepositoryMock_GetRetainedQuotesForAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetainedQuotesForAddress'
type PegoutQuoteRepositoryMock_GetRetainedQuotesForAddress_Call struct {
	*mock.Call
}

// GetRetainedQuotesForAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - states ...quote.PegoutState
func (_e *PegoutQuoteRepositoryMock_Expecter) GetRetainedQuotesForAddress(ctx interface{}, address interface{}, states ...interface{}) *PegoutQuoteRepositoryMock_GetRetainedQuotesForAddress_Call {
	return &PegoutQuoteRepositoryMock_GetRetainedQuotesForAddress_Call{Call: _e.mock.On("GetRetainedQuotesForAddress",
		append([]interface{}{ctx, address}, states...)...)}
}

func (_c *PegoutQuoteRepositoryMock_GetRetainedQuotesForAddress_Call) Run(run func(ctx context.Context, address string, states ...quote.PegoutState)) *PegoutQuoteRepositoryMock_GetRetainedQuotesForAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]quote.PegoutState, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(quote.PegoutState)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetRetainedQuotesForAddress_Call) Return(_a0 []quote.RetainedPegoutQuote, _a1 error) *PegoutQuoteRepositoryMock_GetRetainedQuotesForAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetRetainedQuotesForAddress_Call) RunAndReturn(run func(context.Context, string, ...quote.PegoutState) ([]quote.RetainedPegoutQuote, error)) *PegoutQuoteRepositoryMock_GetRetainedQuotesForAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetRetainedQuotesInBatch provides a mock function with given fields: ctx, batch
func (_m *PegoutQuoteRepositoryMock) GetRetainedQuotesInBatch(ctx context.Context, batch rootstock.BatchPegOut) ([]quote.RetainedPegoutQuote, error) {
	ret := _m.Called(ctx, batch)

	if len(ret) == 0 {
		panic("no return value specified for GetRetainedQuotesInBatch")
	}

	var r0 []quote.RetainedPegoutQuote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, rootstock.BatchPegOut) ([]quote.RetainedPegoutQuote, error)); ok {
		return rf(ctx, batch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, rootstock.BatchPegOut) []quote.RetainedPegoutQuote); ok {
		r0 = rf(ctx, batch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]quote.RetainedPegoutQuote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, rootstock.BatchPegOut) error); ok {
		r1 = rf(ctx, batch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegoutQuoteRepositoryMock_GetRetainedQuotesInBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetainedQuotesInBatch'
type PegoutQuoteRepositoryMock_GetRetainedQuotesInBatch_Call struct {
	*mock.Call
}

// GetRetainedQuotesInBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - batch rootstock.BatchPegOut
func (_e *PegoutQuoteRepositoryMock_Expecter) GetRetainedQuotesInBatch(ctx interface{}, batch interface{}) *PegoutQuoteRepositoryMock_GetRetainedQuotesInBatch_Call {
	return &PegoutQuoteRepositoryMock_GetRetainedQuotesInBatch_Call{Call: _e.mock.On("GetRetainedQuotesInBatch", ctx, batch)}
}

func (_c *PegoutQuoteRepositoryMock_GetRetainedQuotesInBatch_Call) Run(run func(ctx context.Context, batch rootstock.BatchPegOut)) *PegoutQuoteRepositoryMock_GetRetainedQuotesInBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rootstock.BatchPegOut))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetRetainedQuotesInBatch_Call) Return(_a0 []quote.RetainedPegoutQuote, _a1 error) *PegoutQuoteRepositoryMock_GetRetainedQuotesInBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_GetRetainedQuotesInBatch_Call) RunAndReturn(run func(context.Context, rootstock.BatchPegOut) ([]quote.RetainedPegoutQuote, error)) *PegoutQuoteRepositoryMock_GetRetainedQuotesInBatch_Call {
	_c.Call.Return(run)
	return _c
}

// InsertQuote provides a mock function with given fields: ctx, _a1
func (_m *PegoutQuoteRepositoryMock) InsertQuote(ctx context.Context, _a1 quote.CreatedPegoutQuote) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InsertQuote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, quote.CreatedPegoutQuote) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegoutQuoteRepositoryMock_InsertQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertQuote'
type PegoutQuoteRepositoryMock_InsertQuote_Call struct {
	*mock.Call
}

// InsertQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 quote.CreatedPegoutQuote
func (_e *PegoutQuoteRepositoryMock_Expecter) InsertQuote(ctx interface{}, _a1 interface{}) *PegoutQuoteRepositoryMock_InsertQuote_Call {
	return &PegoutQuoteRepositoryMock_InsertQuote_Call{Call: _e.mock.On("InsertQuote", ctx, _a1)}
}

func (_c *PegoutQuoteRepositoryMock_InsertQuote_Call) Run(run func(ctx context.Context, _a1 quote.CreatedPegoutQuote)) *PegoutQuoteRepositoryMock_InsertQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(quote.CreatedPegoutQuote))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_InsertQuote_Call) Return(_a0 error) *PegoutQuoteRepositoryMock_InsertQuote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_InsertQuote_Call) RunAndReturn(run func(context.Context, quote.CreatedPegoutQuote) error) *PegoutQuoteRepositoryMock_InsertQuote_Call {
	_c.Call.Return(run)
	return _c
}

// InsertRetainedQuote provides a mock function with given fields: ctx, _a1
func (_m *PegoutQuoteRepositoryMock) InsertRetainedQuote(ctx context.Context, _a1 quote.RetainedPegoutQuote) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InsertRetainedQuote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, quote.RetainedPegoutQuote) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegoutQuoteRepositoryMock_InsertRetainedQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertRetainedQuote'
type PegoutQuoteRepositoryMock_InsertRetainedQuote_Call struct {
	*mock.Call
}

// InsertRetainedQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 quote.RetainedPegoutQuote
func (_e *PegoutQuoteRepositoryMock_Expecter) InsertRetainedQuote(ctx interface{}, _a1 interface{}) *PegoutQuoteRepositoryMock_InsertRetainedQuote_Call {
	return &PegoutQuoteRepositoryMock_InsertRetainedQuote_Call{Call: _e.mock.On("InsertRetainedQuote", ctx, _a1)}
}

func (_c *PegoutQuoteRepositoryMock_InsertRetainedQuote_Call) Run(run func(ctx context.Context, _a1 quote.RetainedPegoutQuote)) *PegoutQuoteRepositoryMock_InsertRetainedQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(quote.RetainedPegoutQuote))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_InsertRetainedQuote_Call) Return(_a0 error) *PegoutQuoteRepositoryMock_InsertRetainedQuote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_InsertRetainedQuote_Call) RunAndReturn(run func(context.Context, quote.RetainedPegoutQuote) error) *PegoutQuoteRepositoryMock_InsertRetainedQuote_Call {
	_c.Call.Return(run)
	return _c
}

// ListPegoutDepositsByAddress provides a mock function with given fields: ctx, address
func (_m *PegoutQuoteRepositoryMock) ListPegoutDepositsByAddress(ctx context.Context, address string) ([]quote.PegoutDeposit, error) {
	ret := _m.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for ListPegoutDepositsByAddress")
	}

	var r0 []quote.PegoutDeposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]quote.PegoutDeposit, error)); ok {
		return rf(ctx, address)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []quote.PegoutDeposit); ok {
		r0 = rf(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]quote.PegoutDeposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PegoutQuoteRepositoryMock_ListPegoutDepositsByAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPegoutDepositsByAddress'
type PegoutQuoteRepositoryMock_ListPegoutDepositsByAddress_Call struct {
	*mock.Call
}

// ListPegoutDepositsByAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *PegoutQuoteRepositoryMock_Expecter) ListPegoutDepositsByAddress(ctx interface{}, address interface{}) *PegoutQuoteRepositoryMock_ListPegoutDepositsByAddress_Call {
	return &PegoutQuoteRepositoryMock_ListPegoutDepositsByAddress_Call{Call: _e.mock.On("ListPegoutDepositsByAddress", ctx, address)}
}

func (_c *PegoutQuoteRepositoryMock_ListPegoutDepositsByAddress_Call) Run(run func(ctx context.Context, address string)) *PegoutQuoteRepositoryMock_ListPegoutDepositsByAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_ListPegoutDepositsByAddress_Call) Return(_a0 []quote.PegoutDeposit, _a1 error) *PegoutQuoteRepositoryMock_ListPegoutDepositsByAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_ListPegoutDepositsByAddress_Call) RunAndReturn(run func(context.Context, string) ([]quote.PegoutDeposit, error)) *PegoutQuoteRepositoryMock_ListPegoutDepositsByAddress_Call {
	_c.Call.Return(run)
	return _c
}

// ListQuotesByDateRange provides a mock function with given fields: ctx, startDate, endDate, page, perPage
func (_m *PegoutQuoteRepositoryMock) ListQuotesByDateRange(ctx context.Context, startDate time.Time, endDate time.Time, page int, perPage int) ([]quote.PegoutQuoteWithRetained, int, error) {
	ret := _m.Called(ctx, startDate, endDate, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for ListQuotesByDateRange")
	}

	var r0 []quote.PegoutQuoteWithRetained
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) ([]quote.PegoutQuoteWithRetained, int, error)); ok {
		return rf(ctx, startDate, endDate, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) []quote.PegoutQuoteWithRetained); ok {
		r0 = rf(ctx, startDate, endDate, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]quote.PegoutQuoteWithRetained)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int, int) int); ok {
		r1 = rf(ctx, startDate, endDate, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, time.Time, time.Time, int, int) error); ok {
		r2 = rf(ctx, startDate, endDate, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PegoutQuoteRepositoryMock_ListQuotesByDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQuotesByDateRange'
type PegoutQuoteRepositoryMock_ListQuotesByDateRange_Call struct {
	*mock.Call
}

// ListQuotesByDateRange is a helper method to define mock.On call
//   - ctx context.Context
//   - startDate time.Time
//   - endDate time.Time
//   - page int
//   - perPage int
func (_e *PegoutQuoteRepositoryMock_Expecter) ListQuotesByDateRange(ctx interface{}, startDate interface{}, endDate interface{}, page interface{}, perPage interface{}) *PegoutQuoteRepositoryMock_ListQuotesByDateRange_Call {
	return &PegoutQuoteRepositoryMock_ListQuotesByDateRange_Call{Call: _e.mock.On("ListQuotesByDateRange", ctx, startDate, endDate, page, perPage)}
}

func (_c *PegoutQuoteRepositoryMock_ListQuotesByDateRange_Call) Run(run func(ctx context.Context, startDate time.Time, endDate time.Time, page int, perPage int)) *PegoutQuoteRepositoryMock_ListQuotesByDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_ListQuotesByDateRange_Call) Return(_a0 []quote.PegoutQuoteWithRetained, _a1 int, _a2 error) *PegoutQuoteRepositoryMock_ListQuotesByDateRange_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_ListQuotesByDateRange_Call) RunAndReturn(run func(context.Context, time.Time, time.Time, int, int) ([]quote.PegoutQuoteWithRetained, int, error)) *PegoutQuoteRepositoryMock_ListQuotesByDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRetainedQuote provides a mock function with given fields: ctx, _a1
func (_m *PegoutQuoteRepositoryMock) UpdateRetainedQuote(ctx context.Context, _a1 quote.RetainedPegoutQuote) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRetainedQuote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, quote.RetainedPegoutQuote) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegoutQuoteRepositoryMock_UpdateRetainedQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRetainedQuote'
type PegoutQuoteRepositoryMock_UpdateRetainedQuote_Call struct {
	*mock.Call
}

// UpdateRetainedQuote is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 quote.RetainedPegoutQuote
func (_e *PegoutQuoteRepositoryMock_Expecter) UpdateRetainedQuote(ctx interface{}, _a1 interface{}) *PegoutQuoteRepositoryMock_UpdateRetainedQuote_Call {
	return &PegoutQuoteRepositoryMock_UpdateRetainedQuote_Call{Call: _e.mock.On("UpdateRetainedQuote", ctx, _a1)}
}

func (_c *PegoutQuoteRepositoryMock_UpdateRetainedQuote_Call) Run(run func(ctx context.Context, _a1 quote.RetainedPegoutQuote)) *PegoutQuoteRepositoryMock_UpdateRetainedQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(quote.RetainedPegoutQuote))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_UpdateRetainedQuote_Call) Return(_a0 error) *PegoutQuoteRepositoryMock_UpdateRetainedQuote_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_UpdateRetainedQuote_Call) RunAndReturn(run func(context.Context, quote.RetainedPegoutQuote) error) *PegoutQuoteRepositoryMock_UpdateRetainedQuote_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRetainedQuotes provides a mock function with given fields: ctx, quotes
func (_m *PegoutQuoteRepositoryMock) UpdateRetainedQuotes(ctx context.Context, quotes []quote.RetainedPegoutQuote) error {
	ret := _m.Called(ctx, quotes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRetainedQuotes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []quote.RetainedPegoutQuote) error); ok {
		r0 = rf(ctx, quotes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegoutQuoteRepositoryMock_UpdateRetainedQuotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRetainedQuotes'
type PegoutQuoteRepositoryMock_UpdateRetainedQuotes_Call struct {
	*mock.Call
}

// UpdateRetainedQuotes is a helper method to define mock.On call
//   - ctx context.Context
//   - quotes []quote.RetainedPegoutQuote
func (_e *PegoutQuoteRepositoryMock_Expecter) UpdateRetainedQuotes(ctx interface{}, quotes interface{}) *PegoutQuoteRepositoryMock_UpdateRetainedQuotes_Call {
	return &PegoutQuoteRepositoryMock_UpdateRetainedQuotes_Call{Call: _e.mock.On("UpdateRetainedQuotes", ctx, quotes)}
}

func (_c *PegoutQuoteRepositoryMock_UpdateRetainedQuotes_Call) Run(run func(ctx context.Context, quotes []quote.RetainedPegoutQuote)) *PegoutQuoteRepositoryMock_UpdateRetainedQuotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]quote.RetainedPegoutQuote))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_UpdateRetainedQuotes_Call) Return(_a0 error) *PegoutQuoteRepositoryMock_UpdateRetainedQuotes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_UpdateRetainedQuotes_Call) RunAndReturn(run func(context.Context, []quote.RetainedPegoutQuote) error) *PegoutQuoteRepositoryMock_UpdateRetainedQuotes_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPegoutDeposit provides a mock function with given fields: ctx, deposit
func (_m *PegoutQuoteRepositoryMock) UpsertPegoutDeposit(ctx context.Context, deposit quote.PegoutDeposit) error {
	ret := _m.Called(ctx, deposit)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPegoutDeposit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, quote.PegoutDeposit) error); ok {
		r0 = rf(ctx, deposit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegoutQuoteRepositoryMock_UpsertPegoutDeposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPegoutDeposit'
type PegoutQuoteRepositoryMock_UpsertPegoutDeposit_Call struct {
	*mock.Call
}

// UpsertPegoutDeposit is a helper method to define mock.On call
//   - ctx context.Context
//   - deposit quote.PegoutDeposit
func (_e *PegoutQuoteRepositoryMock_Expecter) UpsertPegoutDeposit(ctx interface{}, deposit interface{}) *PegoutQuoteRepositoryMock_UpsertPegoutDeposit_Call {
	return &PegoutQuoteRepositoryMock_UpsertPegoutDeposit_Call{Call: _e.mock.On("UpsertPegoutDeposit", ctx, deposit)}
}

func (_c *PegoutQuoteRepositoryMock_UpsertPegoutDeposit_Call) Run(run func(ctx context.Context, deposit quote.PegoutDeposit)) *PegoutQuoteRepositoryMock_UpsertPegoutDeposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(quote.PegoutDeposit))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_UpsertPegoutDeposit_Call) Return(_a0 error) *PegoutQuoteRepositoryMock_UpsertPegoutDeposit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_UpsertPegoutDeposit_Call) RunAndReturn(run func(context.Context, quote.PegoutDeposit) error) *PegoutQuoteRepositoryMock_UpsertPegoutDeposit_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPegoutDeposits provides a mock function with given fields: ctx, deposits
func (_m *PegoutQuoteRepositoryMock) UpsertPegoutDeposits(ctx context.Context, deposits []quote.PegoutDeposit) error {
	ret := _m.Called(ctx, deposits)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPegoutDeposits")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []quote.PegoutDeposit) error); ok {
		r0 = rf(ctx, deposits)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PegoutQuoteRepositoryMock_UpsertPegoutDeposits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPegoutDeposits'
type PegoutQuoteRepositoryMock_UpsertPegoutDeposits_Call struct {
	*mock.Call
}

// UpsertPegoutDeposits is a helper method to define mock.On call
//   - ctx context.Context
//   - deposits []quote.PegoutDeposit
func (_e *PegoutQuoteRepositoryMock_Expecter) UpsertPegoutDeposits(ctx interface{}, deposits interface{}) *PegoutQuoteRepositoryMock_UpsertPegoutDeposits_Call {
	return &PegoutQuoteRepositoryMock_UpsertPegoutDeposits_Call{Call: _e.mock.On("UpsertPegoutDeposits", ctx, deposits)}
}

func (_c *PegoutQuoteRepositoryMock_UpsertPegoutDeposits_Call) Run(run func(ctx context.Context, deposits []quote.PegoutDeposit)) *PegoutQuoteRepositoryMock_UpsertPegoutDeposits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]quote.PegoutDeposit))
	})
	return _c
}

func (_c *PegoutQuoteRepositoryMock_UpsertPegoutDeposits_Call) Return(_a0 error) *PegoutQuoteRepositoryMock_UpsertPegoutDeposits_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PegoutQuoteRepositoryMock_UpsertPegoutDeposits_Call) RunAndReturn(run func(context.Context, []quote.PegoutDeposit) error) *PegoutQuoteRepositoryMock_UpsertPegoutDeposits_Call {
	_c.Call.Return(run)
	return _c
}

// NewPegoutQuoteRepositoryMock creates a new instance of PegoutQuoteRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPegoutQuoteRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PegoutQuoteRepositoryMock {
	mock := &PegoutQuoteRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
