// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	liquidity_provider "github.com/rsksmart/liquidity-provider-server/internal/entities/liquidity_provider"
	mock "github.com/stretchr/testify/mock"
)

// ServerInfoUseCaseMock is an autogenerated mock type for the ServerInfoUseCase type
type ServerInfoUseCaseMock struct {
	mock.Mock
}

type ServerInfoUseCaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServerInfoUseCaseMock) EXPECT() *ServerInfoUseCaseMock_Expecter {
	return &ServerInfoUseCaseMock_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with no fields
func (_m *ServerInfoUseCaseMock) Run() (liquidity_provider.ServerInfo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 liquidity_provider.ServerInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() (liquidity_provider.ServerInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() liquidity_provider.ServerInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(liquidity_provider.ServerInfo)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServerInfoUseCaseMock_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type ServerInfoUseCaseMock_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *ServerInfoUseCaseMock_Expecter) Run() *ServerInfoUseCaseMock_Run_Call {
	return &ServerInfoUseCaseMock_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *ServerInfoUseCaseMock_Run_Call) Run(run func()) *ServerInfoUseCaseMock_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServerInfoUseCaseMock_Run_Call) Return(_a0 liquidity_provider.ServerInfo, _a1 error) *ServerInfoUseCaseMock_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServerInfoUseCaseMock_Run_Call) RunAndReturn(run func() (liquidity_provider.ServerInfo, error)) *ServerInfoUseCaseMock_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewServerInfoUseCaseMock creates a new instance of ServerInfoUseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerInfoUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerInfoUseCaseMock {
	mock := &ServerInfoUseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
