// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	liquidity_provider "github.com/rsksmart/liquidity-provider-server/internal/entities/liquidity_provider"

	mock "github.com/stretchr/testify/mock"
)

// SetCredentialsUseCaseMock is an autogenerated mock type for the SetCredentialsUseCase type
type SetCredentialsUseCaseMock struct {
	mock.Mock
}

type SetCredentialsUseCaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SetCredentialsUseCaseMock) EXPECT() *SetCredentialsUseCaseMock_Expecter {
	return &SetCredentialsUseCaseMock_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, oldCredentials, newCredentials
func (_m *SetCredentialsUseCaseMock) Run(ctx context.Context, oldCredentials liquidity_provider.Credentials, newCredentials liquidity_provider.Credentials) error {
	ret := _m.Called(ctx, oldCredentials, newCredentials)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, liquidity_provider.Credentials, liquidity_provider.Credentials) error); ok {
		r0 = rf(ctx, oldCredentials, newCredentials)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetCredentialsUseCaseMock_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type SetCredentialsUseCaseMock_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - oldCredentials liquidity_provider.Credentials
//   - newCredentials liquidity_provider.Credentials
func (_e *SetCredentialsUseCaseMock_Expecter) Run(ctx interface{}, oldCredentials interface{}, newCredentials interface{}) *SetCredentialsUseCaseMock_Run_Call {
	return &SetCredentialsUseCaseMock_Run_Call{Call: _e.mock.On("Run", ctx, oldCredentials, newCredentials)}
}

func (_c *SetCredentialsUseCaseMock_Run_Call) Run(run func(ctx context.Context, oldCredentials liquidity_provider.Credentials, newCredentials liquidity_provider.Credentials)) *SetCredentialsUseCaseMock_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(liquidity_provider.Credentials), args[2].(liquidity_provider.Credentials))
	})
	return _c
}

func (_c *SetCredentialsUseCaseMock_Run_Call) Return(_a0 error) *SetCredentialsUseCaseMock_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SetCredentialsUseCaseMock_Run_Call) RunAndReturn(run func(context.Context, liquidity_provider.Credentials, liquidity_provider.Credentials) error) *SetCredentialsUseCaseMock_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewSetCredentialsUseCaseMock creates a new instance of SetCredentialsUseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSetCredentialsUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SetCredentialsUseCaseMock {
	mock := &SetCredentialsUseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
