apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true
    uid: prometheus-uid
  - name: Loki
    type: loki
    url: http://loki:3100
    isDefault: false
    access: proxy
    editable: true
    uid: loki-uid